# First steps
* PySpark Dataframe
* Reading The Dataset
* Checking the Datatypes of the Column(Schema)
* Selecting Columns And Indexing
* Check Describe option similar to Pandas
* Adding Columns
* Dropping columns
* Renaming Columns

# Check assumptions

# Error no catalog

utilizar where ou which python com o environment ativo

```bash
which python
```
```bash
where python
```

Na localização encontrada adicionar Lib\site-packages\pyspark\jars

In [31]:
import pyspark

In [32]:
pyspark.__version__

'4.1.1'

In [33]:
#import findspark
#findspark.init()

Se der erro:

```Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.net.BindException: Cannot assign requested address: bind: Service 'sparkDriver' failed after 16 retries (on a random free port)! Consider explicitly setting the appropriate binding address for the service 'sparkDriver' (for example spark.driver.bindAddress for SparkDriver) to the correct binding address```

In [34]:
conf = pyspark.SparkConf().set('spark.driver.host','localhost')

In [35]:
# Import PySpark and create a SparkSession
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("ImportData").getOrCreate()

#spark = SparkSession.builder \
#    .appName("ImportData") \
#    .config("spark.executor.memory", "4g") \
#    .getOrCreate()

In [36]:
spark

# Comandos jupyter notebook


* a = above abre célula acima
* b = bellow abre célula abaixo
* dd = apaga célula
* x corta célula
* v cola célula
* m modo markdown
* y modo código

# Markdown

* \# Titulo 1
* \## Titulo 2
* \* unnumbered bullet
* \1. numbered bullet

1. Item
2. Item
3. Item

[Google](http://www.google.com)

# Dados disponíveis no repositório

* O dataset `btc_04h_usdt_binance.parquet` já está incluído no projeto
* Formato Parquet — otimizado para Big Data (columnar, comprimido)

In [37]:
# linux/mac
!pwd
# windows
!cd

/home/sobreiro/git/teaching/big_data/notebooks

In [38]:
import pandas as pd

df_pandas = pd.read_parquet("./../data/btc_04h_usdt_binance.parquet")

In [39]:
type(df_pandas)

pandas.DataFrame

In [40]:
df_pandas.describe()

,open_time,open,high,low,close,volume,close_time,quote_vol,trades,taker_buy_base,...,slope_rsi,morningstar,hammer,piercing,3soldiers,engulfing,rsi_ema7,obv_ema7,slope_rsi_ema7,slope_obv_ema7
count,18737,18737.000000,18737.000000,18737.000000,18737.000000,18737.000000,18737,1.873700e+04,1.873700e+04,18737.000000,...,18715.000000,18737.000000,18737.000000,18737.0,18737.000000,18737.000000,18724.000000,1.873700e+04,18715.000000,18728.000000
mean,2021-11-27 20:11:20.151571,36851.506206,37158.718998,36522.644400,36854.919229,10285.335105,2021-11-28 00:11:11.874962,2.944854e+08,3.244524e+05,5107.098768,...,-0.000002,0.256178,2.871324,0.0,0.016011,0.453648,51.239814,1.436217e+06,0.000570,160.034525
min,2017-08-17 04:00:00,2870.900000,3148.000000,2817.000000,2919.000000,0.000000,2017-08-17 07:59:59.999000,0.000000e+00,0.000000e+00,0.000000,...,-6.597144,0.000000,0.000000,0.0,0.000000,-100.000000,9.434184,-8.762407e+05,-5.002780,-91121.046679
25%,2019-10-09 08:00:00,9205.100000,9273.200000,9125.310000,9205.170000,3368.923010,2019-10-09 11:59:59.999000,5.959047e+07,6.764500e+04,1662.863627,...,-0.951393,0.000000,0.000000,0.0,0.000000,0.000000,43.214178,-5.666638e+03,-0.719774,-1160.012597
50%,2021-11-28 04:00:00,26786.010000,26904.980000,26605.050000,26795.010000,5972.525580,2021-11-28 07:59:59.999000,1.717739e+08,1.740810e+05,2987.005580,...,0.012481,0.000000,0.000000,0.0,0.000000,0.000000,50.743987,1.634566e+06,0.004796,32.537625
75%,2024-01-17 20:00:00,57887.960000,58400.000000,57267.980000,57889.100000,10970.361240,2024-01-17 23:59:59.999000,3.954179e+08,3.924230e+05,5447.199101,...,0.964620,0.000000,0.000000,0.0,0.000000,0.000000,59.232702,3.023454e+06,0.725570,1307.448533
max,2026-03-08 12:00:00,125410.800000,126199.630000,124800.000000,125410.810000,284711.694213,2026-03-08 15:59:59.999000,5.457624e+09,6.089593e+06,141232.701595,...,8.101799,100.000000,100.000000,0.0,100.000000,100.000000,88.814579,3.396603e+06,5.833594,57083.397618
std,NaN,32392.410501,32593.654889,32177.907028,32392.274919,14209.960973,NaN,3.672437e+08,4.172700e+05,7075.550804,...,1.495564,5.055047,16.700383,0.0,1.265282,27.282781,11.849211,1.408075e+06,1.116010,5278.237856

In [41]:
df_pandas.head()

,open_time,open,high,low,close,volume,close_time,quote_vol,trades,taker_buy_base,...,slope_rsi,morningstar,hammer,piercing,3soldiers,engulfing,rsi_ema7,obv_ema7,slope_rsi_ema7,slope_obv_ema7
0,2017-08-17 04:00:00,4261.48,4349.99,4261.32,4349.99,82.088865,2017-08-17 07:59:59.999,3.531943e+05,334,64.013727,...,NaN,0,0,0,0,0,NaN,82.088865,NaN,NaN
1,2017-08-17 08:00:00,4333.32,4485.39,4333.32,4427.30,63.619882,2017-08-17 11:59:59.999,2.825012e+05,248,58.787633,...,NaN,0,0,0,0,0,NaN,97.993835,NaN,NaN
2,2017-08-17 12:00:00,4436.06,4485.39,4333.42,4352.34,174.562001,2017-08-17 15:59:59.999,7.742388e+05,858,125.184133,...,NaN,0,0,0,0,0,NaN,66.282063,NaN,NaN
3,2017-08-17 16:00:00,4352.33,4354.84,4200.74,4325.23,225.109716,2017-08-17 19:59:59.999,9.652911e+05,986,165.036363,...,NaN,0,0,0,0,0,NaN,-13.779195,NaN,NaN
4,2017-08-17 20:00:00,4307.56,4369.69,4258.56,4285.08,249.769913,2017-08-17 23:59:59.999,1.079545e+06,1001,203.226685,...,NaN,0,0,0,0,0,NaN,-136.267617,NaN,NaN

In [42]:
df_pandas.info()

<class 'pandas.DataFrame'>
RangeIndex: 18737 entries, 0 to 18736
Columns: 112 entries, open_time to slope_obv_ema7
dtypes: datetime64[us](2), float64(102), int32(5), int64(1), str(2)
memory usage: 15.8 MB

In [43]:
spark

In [ ]:
# Ler dados BTC em formato Parquet (dados reais da Binance)
df_btc = spark.read.parquet("./../data/btc_04h_usdt_binance.parquet")

In [45]:
type(df_pandas)

pandas.DataFrame

In [46]:
type(df_btc)

pyspark.sql.classic.dataframe.DataFrame

In [47]:
df_btc.head(5)

[Row(open_time=datetime.datetime(2017, 8, 17, 4, 0), open=4261.48, high=4349.99, low=4261.32, close=4349.99, volume=82.088865, close_time=datetime.datetime(2017, 8, 17, 7, 59, 59, 999000), quote_vol=353194.33293028, trades=334, taker_buy_base=64.013727, taker_buy_quote=275647.42191079, ignore='0', symbol='BTCUSDT', volume_adi=82.088865, volume_obv=82.088865, volume_cmf=None, volume_fi=None, volume_em=None, volume_sma_em=None, volume_vpt=-71.42359467918801, volume_vwap=None, volume_mfi=None, volume_nvi=1000.0, volatility_bbm=None, volatility_bbh=None, volatility_bbl=None, volatility_bbw=None, volatility_bbp=None, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=None, volatility_kch=4409.1033333333335, volatility_kcl=4231.763333333333, volatility_kcw=None, volatility_kcp=0.666666666666665, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=None, volatility_dch=None, volatility_dcm=None, volatility_dcw=None, volatility_dcp=None, volatility_atr=0.0, volatility_ui=None, trend_macd=None, trend_macd_signal=None, trend_macd_diff=None, trend_sma_fast=None, trend_sma_slow=None, trend_ema_fast=None, trend_ema_slow=None, trend_vortex_ind_pos=None, trend_vortex_ind_neg=None, trend_vortex_ind_diff=None, trend_trix=None, trend_mass_index=None, trend_dpo=None, trend_kst=None, trend_kst_sig=None, trend_kst_diff=None, trend_ichimoku_conv=None, trend_ichimoku_base=None, trend_ichimoku_a=None, trend_ichimoku_b=4305.655, trend_stc=None, trend_adx=0.0, trend_adx_pos=0.0, trend_adx_neg=0.0, trend_cci=None, trend_visual_ichimoku_a=36800.77023033349, trend_visual_ichimoku_b=36650.080737310906, trend_aroon_up=None, trend_aroon_down=None, trend_aroon_ind=None, trend_psar_up=None, trend_psar_down=None, trend_psar_up_indicator=0.0, trend_psar_down_indicator=0.0, momentum_rsi=None, momentum_stoch_rsi=None, momentum_stoch_rsi_k=None, momentum_stoch_rsi_d=None, momentum_tsi=None, momentum_uo=None, momentum_stoch=None, momentum_stoch_signal=None, momentum_wr=None, momentum_ao=None, momentum_roc=None, momentum_ppo=None, momentum_ppo_signal=None, momentum_ppo_hist=None, momentum_kama=None, others_dr=-88.19698946294015, others_dlr=None, others_cr=0.0, sma200=None, sma50=None, ema200=4349.99, ema50=4349.99, slope=None, slope_obv=None, slope_rsi=None, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=None, obv_ema7=82.088865, slope_rsi_ema7=None, slope_obv_ema7=None),
 Row(open_time=datetime.datetime(2017, 8, 17, 8, 0), open=4333.32, high=4485.39, low=4333.32, close=4427.3, volume=63.619882, close_time=datetime.datetime(2017, 8, 17, 11, 59, 59, 999000), quote_vol=282501.15774965, trades=248, taker_buy_base=58.787633, taker_buy_quote=261054.05115395, ignore='0', symbol='BTCUSDT', volume_adi=97.10377632360104, volume_obv=145.708747, volume_cmf=None, volume_fi=None, volume_em=24787312557.41736, volume_sma_em=None, volume_vpt=-71.269226146657, volume_vwap=None, volume_mfi=None, volume_nvi=1017.7724546493212, volatility_bbm=None, volatility_bbh=None, volatility_bbl=None, volatility_bbw=None, volatility_bbp=None, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=None, volatility_kch=4488.255, volatility_kcl=4247.514999999999, volatility_kcw=None, volatility_kcp=0.7468015286200891, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=None, volatility_dch=None, volatility_dcm=None, volatility_dcw=None, volatility_dcp=None, volatility_atr=0.0, volatility_ui=None, trend_macd=None, trend_macd_signal=None, trend_macd_diff=None, trend_sma_fast=None, trend_sma_slow=None, trend_ema_fast=None, trend_ema_slow=None, trend_vortex_ind_pos=None, trend_vortex_ind_neg=None, trend_vortex_ind_diff=None, trend_trix=None, trend_mass_index=None, trend_dpo=None, trend_kst=None, trend_kst_sig=None, trend_kst_diff=None, trend_ichimoku_conv=None, trend_ichimoku_base=None, trend_ichimoku_a=None, trend_ichimoku_b=4373.355, trend_stc=None, trend_adx=0.0, trend_adx_pos=0.0, trend_adx_neg=0.0, trend_cci=None, trend_visual_ichimoku_a=36800.77023033349, trend_visual_ichimoku_b=36650.080737310906, trend_aroon_up=None, trend_aroon_down=None, trend_aroon_ind=None, trend_psar_up=None, trend_psar_down=None, trend_psar_up_indicator=0.0, trend_psar_down_indicator=0.0, momentum_rsi=None, momentum_stoch_rsi=None, momentum_stoch_rsi_k=None, momentum_stoch_rsi_d=None, momentum_tsi=None, momentum_uo=None, momentum_stoch=None, momentum_stoch_signal=None, momentum_wr=None, momentum_ao=None, momentum_roc=None, momentum_ppo=None, momentum_ppo_signal=None, momentum_ppo_hist=None, momentum_kama=None, others_dr=1.77724546493212, others_dlr=1.761637118809567, others_cr=1.77724546493212, sma200=None, sma50=None, ema200=4350.759253731344, ema50=4353.021764705883, slope=None, slope_obv=None, slope_rsi=None, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=None, obv_ema7=97.99383549999999, slope_rsi_ema7=None, slope_obv_ema7=None),
 Row(open_time=datetime.datetime(2017, 8, 17, 12, 0), open=4436.06, high=4485.39, low=4333.42, close=4352.34, volume=174.562001, close_time=datetime.datetime(2017, 8, 17, 15, 59, 59, 999000), quote_vol=774238.79831726, trades=858, taker_buy_base=125.184133, taker_buy_quote=555419.7580611, ignore='0', symbol='BTCUSDT', volume_adi=-33.99289521768992, volume_obv=-28.85325400000002, volume_cmf=None, volume_fi=None, volume_em=4352894.648605486, volume_sma_em=None, volume_vpt=-1.8248823285697195, volume_vwap=None, volume_mfi=None, volume_nvi=1017.7724546493212, volatility_bbm=None, volatility_bbh=None, volatility_bbl=None, volatility_bbw=None, volatility_bbp=None, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=None, volatility_kch=4506.2877777777785, volatility_kcl=4244.481111111111, volatility_kcw=None, volatility_kcp=0.41197915340412267, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=None, volatility_dch=None, volatility_dcm=None, volatility_dcw=None, volatility_dcp=None, volatility_atr=0.0, volatility_ui=None, trend_macd=None, trend_macd_signal=None, trend_macd_diff=None, trend_sma_fast=None, trend_sma_slow=None, trend_ema_fast=None, trend_ema_slow=None, trend_vortex_ind_pos=None, trend_vortex_ind_neg=None, trend_vortex_ind_diff=None, trend_trix=None, trend_mass_index=None, trend_dpo=None, trend_kst=None, trend_kst_sig=None, trend_kst_diff=None, trend_ichimoku_conv=None, trend_ichimoku_base=None, trend_ichimoku_a=None, trend_ichimoku_b=4373.355, trend_stc=None, trend_adx=0.0, trend_adx_pos=0.0, trend_adx_neg=0.0, trend_cci=None, trend_visual_ichimoku_a=36800.77023033349, trend_visual_ichimoku_b=36650.080737310906, trend_aroon_up=None, trend_aroon_down=None, trend_aroon_ind=None, trend_psar_up=None, trend_psar_down=4349.99, trend_psar_up_indicator=0.0, trend_psar_down_indicator=1.0, momentum_rsi=None, momentum_stoch_rsi=None, momentum_stoch_rsi_k=None, momentum_stoch_rsi_d=None, momentum_tsi=None, momentum_uo=None, momentum_stoch=None, momentum_stoch_signal=None, momentum_wr=None, momentum_ao=None, momentum_roc=None, momentum_ppo=None, momentum_ppo_signal=None, momentum_ppo_hist=None, momentum_kama=None, others_dr=-1.693131253811575, others_dlr=-1.707628593342747, others_cr=0.054023112696821585, sma200=None, sma50=None, ema200=4350.774982549938, ema50=4352.995028835064, slope=None, slope_obv=None, slope_rsi=None, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=None, obv_ema7=66.28206312499998, slope_rsi_ema7=None, slope_obv_ema7=None),
 Row(open_time=datetime.datetime(2017, 8, 17, 16, 0), open=4352.33, high=4354.84, low=4200.74, close=4325.23, volume=225.109716, close_time=datetime.datetime(2017, 8, 17, 19, 59, 59, 999000), quote_vol=965291.09880366, trades=986, taker_buy_base=165.036363, taker_buy_quote=707808.20092154, ignore='0', symbol='BTCUSDT', volume_adi=104.60807722929104, volume_obv=-253.96297, volume_cmf=None, volume_fi=None, volume_em=-9009771706.166643, volume_sma_em=None, volume_vpt=-4.357734674578788, volume_vwap=None, volume_mfi=None, volume_nvi=1017.7724546493212, volatility_bbm=None, volatility_bbh=None, volatility_bbl=None, volatility_bbw=None, volatility_bbp=None, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=None, volatility_kch=4491.641666666666, volatility_kcl=4218.236666666667, volatility_kcw=None, volatility_kcp=0.3913364178904299, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=None, volatility_dch=None, volatility_dcm=None, volatility_dcw=None, volatility_dcp=None, volatility_atr=0.0, volatility_ui=None, trend_macd=None, trend_macd_signal=None, trend_macd_diff=None, trend_sma_fast=None, trend_sma_slow=None, trend_ema_fast=None, trend_ema_slow=None, trend_vortex_ind_pos=None, trend_vortex_ind_neg=None, trend_vortex_ind_diff=None, trend_trix=None, trend_mass_index=None, trend_dpo=None, trend_kst=None, trend_kst_sig=None, trend_kst_diff=None, trend_ichimoku_conv=None, trend_ichimoku_base=None, trend_ichimoku_a=None, trend_ichimoku_b=4343.0650000000005, trend_stc=None, trend_adx=0.0, trend_adx_pos=0.0, trend_adx_neg=0.0, trend_cci=None, trend_visual_ichimoku_a=36800.77023033349, trend_visual_ichimoku_b=36650.080737310906, trend_aroon_up=None, trend_aroon_down=None, trend_aroon_ind=None, trend_psar_up=4333.42, trend_psar_down=None, trend_psar_up_indicator=1.0, trend_psar_down_indicator=0.0, momentum_rsi=None, momentum_stoch_rsi=None, momentum_stoch_rsi_k=None, momentum_stoch_rsi_d=None, momentum_tsi=None, momentum_uo=None, momentum_stoch=None, momentum_stoch_signal=None, momentum_wr=None, momentum_ao=None, momentum_roc=None, momentum_ppo=None, momentum_ppo_signal=None, momentum_ppo_hist=None, momentum_kama=None, others_dr=-0.622883322534562, others_dlr=-0.6248313341412626, others_cr=-0.5691967107970375, sma200=None, sma50=None, ema200=4350.5208036190925, ema50=4351.906204174865, slope=None, slope_obv=None, slope_rsi=None, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=None, obv_ema7=-13.779195156250019, slope_rsi_ema7=None, slope_obv_ema7=None),
 Row(open_time=datetime.datetime(2017, 8, 17, 20, 0), open=4307.56, high=4369.69, low=4258.56, close=4285.08, volume=249.769913, close_time=datetime.datetime(2017, 8, 17, 23, 59, 59, 999000), quote_vol=1079544.66293121, trades=1001, taker_buy_base=203.226685, taker_buy_quote=878286.96855663, ignore='0', symbol='BTCUSDT', volume_adi=-25.951935784027967, volume_obv=-503.732883, volume_cmf=None, volume_fi=None, volume_em=1616651301.792292, volume_sma_em=None, volume_vpt=-3.7207208761609114, volume_vwap=None, volume_mfi=None, volume_nvi=1017.7724546493212, volatility_bbm=None, volatility_bbh=None, volatility_bbl=None, volatility_bbw=None, volatility_bbp=None, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=None, volatility_kch=4476.428, volatility_kcl=4213.252, volatility_kcw=None, volatility_kcp=0.27292762257956527, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=None, volatility_dch=None, volatility_dcm=None, volatility_dcw=None, volatility_dcp=None, volatility_atr=0.0, volatility_ui=None, trend_macd=None, trend_macd_signal=None, trend_macd_diff=None, trend_sma_fast=None, trend_sma_slow=None, trend_ema_fast=None, trend_ema_slow=None, trend_vortex_ind_pos=None, trend_vortex_ind_neg=None, trend_vortex_ind_diff=None, trend_trix=None, trend_mass_index=None, trend_dpo=None, trend_kst=None, trend_kst_sig=None, trend_kst_diff=None, trend_ichimoku_conv=None, trend_ichimoku_base=None, trend_ichimoku_a=None, trend_ichimoku_b=4343.0650000000005, trend_stc=None, trend_adx=0.0, trend_adx_pos=0.0, trend_adx_neg=0.0, trend_cci=None, trend_visual_ichimoku_a=36800.77023033349, trend_visual_ichimoku_b=36650.080737310906, trend_aroon_up=None, trend_aroon_down=None, trend_aroon_ind=None, trend_psar_up=None, trend_psar_down=4354.84, trend_psar_up_indicator=0.0, trend_psar_down_indicator=1.0, momentum_rsi=None, momentum_stoch_rsi=None, momentum_stoch_rsi_k=None, momentum_stoch_rsi_d=None, momentum_tsi=None, momentum_uo=None, momentum_stoch=None, momentum_stoch_signal=None, momentum_wr=None, momentum_ao=None, momentum_roc=None, momentum_ppo=None, momentum_ppo_signal=None, momentum_ppo_hist=None, momentum_kama=None, others_dr=-0.9282743345440547, others_dlr=-0.9326096506869774, others_cr=-1.4921873383616946, sma200=None, sma50=None, ema200=4349.869651344276, ema50=4349.285568717027, slope=None, slope_obv=None, slope_rsi=None, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=None, obv_ema7=-136.2676171171875, slope_rsi_ema7=None, slope_obv_ema7=None)]

In [48]:
df_btc.show(5)

+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+------------------+----------+---------+--------------------+-------------+-------------------+-----------+----------+------------------+--------------+--------------+--------------+--------------+--------------+---------------+---------------+--------------+------------------+-----------------+--------------+-------------------+---------------+---------------+--------------+--------------+--------------+--------------+--------------+--------------+-------------+----------+-----------------+---------------+--------------+--------------+--------------+--------------+--------------------+--------------------+---------------------+----------+----------------+---------+---------+-------------+--------------+-------------------+-------------------+----------------+------------------+---------+---------+-------------+-------------+---------+-----------------------+-----------------------+--------------+----------------+---------------+-------------+---------------+-----------------------+-------------------------+------------+------------------+--------------------+--------------------+------------+-----------+--------------+---------------------+-----------+-----------+------------+------------+-------------------+-----------------+-------------+-------------------+-------------------+--------------------+------+-----+------------------+-----------------+-----+---------+---------+-----------+------+--------+---------+---------+--------+-------------------+--------------+--------------+
|          open_time|   open|   high|    low|  close|    volume|          close_time|       quote_vol|trades|taker_buy_base|taker_buy_quote|ignore| symbol|         volume_adi|        volume_obv|volume_cmf|volume_fi|           volume_em|volume_sma_em|         volume_vpt|volume_vwap|volume_mfi|        volume_nvi|volatility_bbm|volatility_bbh|volatility_bbl|volatility_bbw|volatility_bbp|volatility_bbhi|volatility_bbli|volatility_kcc|    volatility_kch|   volatility_kcl|volatility_kcw|     volatility_kcp|volatility_kchi|volatility_kcli|volatility_dcl|volatility_dch|volatility_dcm|volatility_dcw|volatility_dcp|volatility_atr|volatility_ui|trend_macd|trend_macd_signal|trend_macd_diff|trend_sma_fast|trend_sma_slow|trend_ema_fast|trend_ema_slow|trend_vortex_ind_pos|trend_vortex_ind_neg|trend_vortex_ind_diff|trend_trix|trend_mass_index|trend_dpo|trend_kst|trend_kst_sig|trend_kst_diff|trend_ichimoku_conv|trend_ichimoku_base|trend_ichimoku_a|  trend_ichimoku_b|trend_stc|trend_adx|trend_adx_pos|trend_adx_neg|trend_cci|trend_visual_ichimoku_a|trend_visual_ichimoku_b|trend_aroon_up|trend_aroon_down|trend_aroon_ind|trend_psar_up|trend_psar_down|trend_psar_up_indicator|trend_psar_down_indicator|momentum_rsi|momentum_stoch_rsi|momentum_stoch_rsi_k|momentum_stoch_rsi_d|momentum_tsi|momentum_uo|momentum_stoch|momentum_stoch_signal|momentum_wr|momentum_ao|momentum_roc|momentum_ppo|momentum_ppo_signal|momentum_ppo_hist|momentum_kama|          others_dr|         others_dlr|           others_cr|sma200|sma50|            ema200|            ema50|slope|slope_obv|slope_rsi|morningstar|hammer|piercing|3soldiers|engulfing|rsi_ema7|           obv_ema7|slope_rsi_ema7|slope_obv_ema7|
+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+------------------+----------+---------+--------------------+-------------+-------------------+-----------+----------+------------------+--------------+--------------+--------------+--------------+--------------+---------------+---------------+--------------+------------------+-----------------+--------------+-------------------+---------------+---------------+--------------+--------------+--------------+--------------+--------------+--------------+-------------+----------+-----------------+---------------+--------------+--------------+--------------+--------------+--------------------+--------------------+---------------------+----------+----------------+---------+---------+-------------+--------------+-------------------+-------------------+----------------+------------------+---------+---------+-------------+-------------+---------+-----------------------+-----------------------+--------------+----------------+---------------+-------------+---------------+-----------------------+-------------------------+------------+------------------+--------------------+--------------------+------------+-----------+--------------+---------------------+-----------+-----------+------------+------------+-------------------+-----------------+-------------+-------------------+-------------------+--------------------+------+-----+------------------+-----------------+-----+---------+---------+-----------+------+--------+---------+---------+--------+-------------------+--------------+--------------+
|2017-08-17 04:00:00|4261.48|4349.99|4261.32|4349.99| 82.088865|2017-08-17 07:59:...| 353194.33293028|   334|     64.013727|275647.42191079|     0|BTCUSDT|          82.088865|         82.088865|      NULL|     NULL|                NULL|         NULL| -71.42359467918801|       NULL|      NULL|            1000.0|          NULL|          NULL|          NULL|          NULL|          NULL|            0.0|            0.0|          NULL|4409.1033333333335|4231.763333333333|          NULL|  0.666666666666665|            0.0|            0.0|          NULL|          NULL|          NULL|          NULL|          NULL|           0.0|         NULL|      NULL|             NULL|           NULL|          NULL|          NULL|          NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|     NULL|     NULL|         NULL|          NULL|               NULL|               NULL|            NULL|          4305.655|     NULL|      0.0|          0.0|          0.0|     NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|         NULL|           NULL|                    0.0|                      0.0|        NULL|              NULL|                NULL|                NULL|        NULL|       NULL|          NULL|                 NULL|       NULL|       NULL|        NULL|        NULL|               NULL|             NULL|         NULL| -88.19698946294015|               NULL|                 0.0|  NULL| NULL|           4349.99|          4349.99| NULL|     NULL|     NULL|          0|     0|       0|        0|        0|    NULL|          82.088865|          NULL|          NULL|
|2017-08-17 08:00:00|4333.32|4485.39|4333.32| 4427.3| 63.619882|2017-08-17 11:59:...| 282501.15774965|   248|     58.787633|261054.05115395|     0|BTCUSDT|  97.10377632360104|        145.708747|      NULL|     NULL|2.478731255741736E10|         NULL|   -71.269226146657|       NULL|      NULL|1017.7724546493212|          NULL|          NULL|          NULL|          NULL|          NULL|            0.0|            0.0|          NULL|          4488.255|4247.514999999999|          NULL| 0.7468015286200891|            0.0|            0.0|          NULL|          NULL|          NULL|          NULL|          NULL|           0.0|         NULL|      NULL|             NULL|           NULL|          NULL|          NULL|          NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|     NULL|     NULL|         NULL|          NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|          0.0|          0.0|     NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|         NULL|           NULL|                    0.0|                      0.0|        NULL|              NULL|                NULL|                NULL|        NULL|       NULL|          NULL|                 NULL|       NULL|       NULL|        NULL|        NULL|               NULL|             NULL|         NULL|   1.77724546493212|  1.761637118809567|    1.77724546493212|  NULL| NULL| 4350.759253731344|4353.021764705883| NULL|     NULL|     NULL|          0|     0|       0|        0|        0|    NULL|  97.99383549999999|          NULL|          NULL|
|2017-08-17 12:00:00|4436.06|4485.39|4333.42|4352.34|174.562001|2017-08-17 15:59:...| 774238.79831726|   858|    125.184133| 555419.7580611|     0|BTCUSDT| -33.99289521768992|-28.85325400000002|      NULL|     NULL|   4352894.648605486|         NULL|-1.8248823285697195|       NULL|      NULL|1017.7724546493212|          NULL|          NULL|          NULL|          NULL|          NULL|            0.0|            0.0|          NULL|4506.2877777777785|4244.481111111111|          NULL|0.41197915340412267|            0.0|            0.0|          NULL|          NULL|          NULL|          NULL|          NULL|           0.0|         NULL|      NULL|             NULL|           NULL|          NULL|          NULL|          NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|     NULL|     NULL|         NULL|          NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|          0.0|          0.0|     NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|         NULL|        4349.99|                    0.0|                      1.0|        NULL|              NULL|                NULL|                NULL|        NULL|       NULL|          NULL|                 NULL|       NULL|       NULL|        NULL|        NULL|               NULL|             NULL|         NULL| -1.693131253811575| -1.707628593342747|0.054023112696821585|  NULL| NULL| 4350.774982549938|4352.995028835064| NULL|     NULL|     NULL|          0|     0|       0|        0|        0|    NULL|  66.28206312499998|          NULL|          NULL|
|2017-08-17 16:00:00|4352.33|4354.84|4200.74|4325.23|225.109716|2017-08-17 19:59:...| 965291.09880366|   986|    165.036363|707808.20092154|     0|BTCUSDT| 104.60807722929104|        -253.96297|      NULL|     NULL|-9.009771706166643E9|         NULL| -4.357734674578788|       NULL|      NULL|1017.7724546493212|          NULL|          NULL|          NULL|          NULL|          NULL|            0.0|            0.0|          NULL| 4491.641666666666|4218.236666666667|          NULL| 0.3913364178904299|            0.0|            0.0|          NULL|          NULL|          NULL|          NULL|          NULL|           0.0|         NULL|      NULL|             NULL|           NULL|          NULL|          NULL|          NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|     NULL|     NULL|         NULL|          NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|          0.0|          0.0|     NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|      4333.42|           NULL|                    1.0|                      0.0|        NULL|              NULL|                NULL|                NULL|        NULL|       NULL|          NULL|                 NULL|       NULL|       NULL|        NULL|        NULL|               NULL|             NULL|         NULL| -0.622883322534562|-0.6248313341412626| -0.5691967107970375|  NULL| NULL|4350.5208036190925|4351.906204174865| NULL|     NULL|     NULL|          0|     0|       0|        0|        0|    NULL|-13.779195156250019|          NULL|          NULL|
|2017-08-17 20:00:00|4307.56|4369.69|4258.56|4285.08|249.769913|2017-08-17 23:59:...|1079544.66293121|  1001|    203.226685|878286.96855663|     0|BTCUSDT|-25.951935784027967|       -503.732883|      NULL|     NULL| 1.616651301792292E9|         NULL|-3.7207208761609114|       NULL|      NULL|1017.7724546493212|          NULL|          NULL|          NULL|          NULL|          NULL|            0.0|            0.0|          NULL|          4476.428|         4213.252|          NULL|0.27292762257956527|            0.0|            0.0|          NULL|          NULL|          NULL|          NULL|          NULL|           0.0|         NULL|      NULL|             NULL|           NULL|          NULL|          NULL|          NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|     NULL|     NULL|         NULL|          NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|          0.0|          0.0|     NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|         NULL|        4354.84|                    0.0|                      1.0|        NULL|              NULL|                NULL|                NULL|        NULL|       NULL|          NULL|                 NULL|       NULL|       NULL|        NULL|        NULL|               NULL|             NULL|         NULL|-0.9282743345440547|-0.9326096506869774| -1.4921873383616946|  NULL| NULL| 4349.869651344276|4349.285568717027| NULL|     NULL|     NULL|          0|     0|       0|        0|        0|    NULL| -136.2676171171875|          NULL|          NULL|
+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+------------------+----------+---------+--------------------+-------------+-------------------+-----------+----------+------------------+--------------+--------------+--------------+--------------+--------------+---------------+---------------+--------------+------------------+-----------------+--------------+-------------------+---------------+---------------+--------------+--------------+--------------+--------------+--------------+--------------+-------------+----------+-----------------+---------------+--------------+--------------+--------------+--------------+--------------------+--------------------+---------------------+----------+----------------+---------+---------+-------------+--------------+-------------------+-------------------+----------------+------------------+---------+---------+-------------+-------------+---------+-----------------------+-----------------------+--------------+----------------+---------------+-------------+---------------+-----------------------+-------------------------+------------+------------------+--------------------+--------------------+------------+-----------+--------------+---------------------+-----------+-----------+------------+------------+-------------------+-----------------+-------------+-------------------+-------------------+--------------------+------+-----+------------------+-----------------+-----+---------+---------+-----------+------+--------+---------+---------+--------+-------------------+--------------+--------------+
only showing top 5 rows

In [49]:
df_btc.toPandas().head()

,open_time,open,high,low,close,volume,close_time,quote_vol,trades,taker_buy_base,...,slope_rsi,morningstar,hammer,piercing,3soldiers,engulfing,rsi_ema7,obv_ema7,slope_rsi_ema7,slope_obv_ema7
0,2017-08-17 04:00:00,4261.48,4349.99,4261.32,4349.99,82.088865,2017-08-17 07:59:59.999,3.531943e+05,334,64.013727,...,NaN,0,0,0,0,0,NaN,82.088865,NaN,NaN
1,2017-08-17 08:00:00,4333.32,4485.39,4333.32,4427.30,63.619882,2017-08-17 11:59:59.999,2.825012e+05,248,58.787633,...,NaN,0,0,0,0,0,NaN,97.993835,NaN,NaN
2,2017-08-17 12:00:00,4436.06,4485.39,4333.42,4352.34,174.562001,2017-08-17 15:59:59.999,7.742388e+05,858,125.184133,...,NaN,0,0,0,0,0,NaN,66.282063,NaN,NaN
3,2017-08-17 16:00:00,4352.33,4354.84,4200.74,4325.23,225.109716,2017-08-17 19:59:59.999,9.652911e+05,986,165.036363,...,NaN,0,0,0,0,0,NaN,-13.779195,NaN,NaN
4,2017-08-17 20:00:00,4307.56,4369.69,4258.56,4285.08,249.769913,2017-08-17 23:59:59.999,1.079545e+06,1001,203.226685,...,NaN,0,0,0,0,0,NaN,-136.267617,NaN,NaN

In [50]:
type(df_btc.toPandas().head())

pandas.DataFrame

In [51]:
df_btc.sample(fraction=0.1).toPandas().head()

,open_time,open,high,low,close,volume,close_time,quote_vol,trades,taker_buy_base,...,slope_rsi,morningstar,hammer,piercing,3soldiers,engulfing,rsi_ema7,obv_ema7,slope_rsi_ema7,slope_obv_ema7
0,2017-08-17 08:00:00,4333.32,4485.39,4333.32,4427.30,63.619882,2017-08-17 11:59:59.999,282501.157750,248,58.787633,...,NaN,0,0,0,0,0,NaN,97.993835,NaN,NaN
1,2017-08-17 16:00:00,4352.33,4354.84,4200.74,4325.23,225.109716,2017-08-17 19:59:59.999,965291.098804,986,165.036363,...,NaN,0,0,0,0,0,NaN,-13.779195,NaN,NaN
2,2017-08-19 00:00:00,4108.37,4184.69,4084.28,4138.55,108.510448,2017-08-19 03:59:59.999,449351.422235,585,92.399174,...,NaN,0,0,0,0,0,NaN,-114.624305,NaN,-7.768325
3,2017-08-19 16:00:00,4036.19,4103.92,3953.40,4076.12,25.925056,2017-08-19 19:59:59.999,104478.702923,161,20.098673,...,NaN,0,0,0,0,0,23.229396,-235.784103,NaN,-22.472371
4,2017-08-19 20:00:00,4088.71,4149.99,4051.47,4139.98,9.350560,2017-08-19 23:59:59.999,38298.551151,113,7.124825,...,NaN,0,0,0,0,0,28.170064,-242.058883,NaN,-28.300540

In [52]:
df_btc.show(5)

+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+------------------+----------+---------+--------------------+-------------+-------------------+-----------+----------+------------------+--------------+--------------+--------------+--------------+--------------+---------------+---------------+--------------+------------------+-----------------+--------------+-------------------+---------------+---------------+--------------+--------------+--------------+--------------+--------------+--------------+-------------+----------+-----------------+---------------+--------------+--------------+--------------+--------------+--------------------+--------------------+---------------------+----------+----------------+---------+---------+-------------+--------------+-------------------+-------------------+----------------+------------------+---------+---------+-------------+-------------+---------+-----------------------+-----------------------+--------------+----------------+---------------+-------------+---------------+-----------------------+-------------------------+------------+------------------+--------------------+--------------------+------------+-----------+--------------+---------------------+-----------+-----------+------------+------------+-------------------+-----------------+-------------+-------------------+-------------------+--------------------+------+-----+------------------+-----------------+-----+---------+---------+-----------+------+--------+---------+---------+--------+-------------------+--------------+--------------+
|          open_time|   open|   high|    low|  close|    volume|          close_time|       quote_vol|trades|taker_buy_base|taker_buy_quote|ignore| symbol|         volume_adi|        volume_obv|volume_cmf|volume_fi|           volume_em|volume_sma_em|         volume_vpt|volume_vwap|volume_mfi|        volume_nvi|volatility_bbm|volatility_bbh|volatility_bbl|volatility_bbw|volatility_bbp|volatility_bbhi|volatility_bbli|volatility_kcc|    volatility_kch|   volatility_kcl|volatility_kcw|     volatility_kcp|volatility_kchi|volatility_kcli|volatility_dcl|volatility_dch|volatility_dcm|volatility_dcw|volatility_dcp|volatility_atr|volatility_ui|trend_macd|trend_macd_signal|trend_macd_diff|trend_sma_fast|trend_sma_slow|trend_ema_fast|trend_ema_slow|trend_vortex_ind_pos|trend_vortex_ind_neg|trend_vortex_ind_diff|trend_trix|trend_mass_index|trend_dpo|trend_kst|trend_kst_sig|trend_kst_diff|trend_ichimoku_conv|trend_ichimoku_base|trend_ichimoku_a|  trend_ichimoku_b|trend_stc|trend_adx|trend_adx_pos|trend_adx_neg|trend_cci|trend_visual_ichimoku_a|trend_visual_ichimoku_b|trend_aroon_up|trend_aroon_down|trend_aroon_ind|trend_psar_up|trend_psar_down|trend_psar_up_indicator|trend_psar_down_indicator|momentum_rsi|momentum_stoch_rsi|momentum_stoch_rsi_k|momentum_stoch_rsi_d|momentum_tsi|momentum_uo|momentum_stoch|momentum_stoch_signal|momentum_wr|momentum_ao|momentum_roc|momentum_ppo|momentum_ppo_signal|momentum_ppo_hist|momentum_kama|          others_dr|         others_dlr|           others_cr|sma200|sma50|            ema200|            ema50|slope|slope_obv|slope_rsi|morningstar|hammer|piercing|3soldiers|engulfing|rsi_ema7|           obv_ema7|slope_rsi_ema7|slope_obv_ema7|
+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+------------------+----------+---------+--------------------+-------------+-------------------+-----------+----------+------------------+--------------+--------------+--------------+--------------+--------------+---------------+---------------+--------------+------------------+-----------------+--------------+-------------------+---------------+---------------+--------------+--------------+--------------+--------------+--------------+--------------+-------------+----------+-----------------+---------------+--------------+--------------+--------------+--------------+--------------------+--------------------+---------------------+----------+----------------+---------+---------+-------------+--------------+-------------------+-------------------+----------------+------------------+---------+---------+-------------+-------------+---------+-----------------------+-----------------------+--------------+----------------+---------------+-------------+---------------+-----------------------+-------------------------+------------+------------------+--------------------+--------------------+------------+-----------+--------------+---------------------+-----------+-----------+------------+------------+-------------------+-----------------+-------------+-------------------+-------------------+--------------------+------+-----+------------------+-----------------+-----+---------+---------+-----------+------+--------+---------+---------+--------+-------------------+--------------+--------------+
|2017-08-17 04:00:00|4261.48|4349.99|4261.32|4349.99| 82.088865|2017-08-17 07:59:...| 353194.33293028|   334|     64.013727|275647.42191079|     0|BTCUSDT|          82.088865|         82.088865|      NULL|     NULL|                NULL|         NULL| -71.42359467918801|       NULL|      NULL|            1000.0|          NULL|          NULL|          NULL|          NULL|          NULL|            0.0|            0.0|          NULL|4409.1033333333335|4231.763333333333|          NULL|  0.666666666666665|            0.0|            0.0|          NULL|          NULL|          NULL|          NULL|          NULL|           0.0|         NULL|      NULL|             NULL|           NULL|          NULL|          NULL|          NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|     NULL|     NULL|         NULL|          NULL|               NULL|               NULL|            NULL|          4305.655|     NULL|      0.0|          0.0|          0.0|     NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|         NULL|           NULL|                    0.0|                      0.0|        NULL|              NULL|                NULL|                NULL|        NULL|       NULL|          NULL|                 NULL|       NULL|       NULL|        NULL|        NULL|               NULL|             NULL|         NULL| -88.19698946294015|               NULL|                 0.0|  NULL| NULL|           4349.99|          4349.99| NULL|     NULL|     NULL|          0|     0|       0|        0|        0|    NULL|          82.088865|          NULL|          NULL|
|2017-08-17 08:00:00|4333.32|4485.39|4333.32| 4427.3| 63.619882|2017-08-17 11:59:...| 282501.15774965|   248|     58.787633|261054.05115395|     0|BTCUSDT|  97.10377632360104|        145.708747|      NULL|     NULL|2.478731255741736E10|         NULL|   -71.269226146657|       NULL|      NULL|1017.7724546493212|          NULL|          NULL|          NULL|          NULL|          NULL|            0.0|            0.0|          NULL|          4488.255|4247.514999999999|          NULL| 0.7468015286200891|            0.0|            0.0|          NULL|          NULL|          NULL|          NULL|          NULL|           0.0|         NULL|      NULL|             NULL|           NULL|          NULL|          NULL|          NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|     NULL|     NULL|         NULL|          NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|          0.0|          0.0|     NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|         NULL|           NULL|                    0.0|                      0.0|        NULL|              NULL|                NULL|                NULL|        NULL|       NULL|          NULL|                 NULL|       NULL|       NULL|        NULL|        NULL|               NULL|             NULL|         NULL|   1.77724546493212|  1.761637118809567|    1.77724546493212|  NULL| NULL| 4350.759253731344|4353.021764705883| NULL|     NULL|     NULL|          0|     0|       0|        0|        0|    NULL|  97.99383549999999|          NULL|          NULL|
|2017-08-17 12:00:00|4436.06|4485.39|4333.42|4352.34|174.562001|2017-08-17 15:59:...| 774238.79831726|   858|    125.184133| 555419.7580611|     0|BTCUSDT| -33.99289521768992|-28.85325400000002|      NULL|     NULL|   4352894.648605486|         NULL|-1.8248823285697195|       NULL|      NULL|1017.7724546493212|          NULL|          NULL|          NULL|          NULL|          NULL|            0.0|            0.0|          NULL|4506.2877777777785|4244.481111111111|          NULL|0.41197915340412267|            0.0|            0.0|          NULL|          NULL|          NULL|          NULL|          NULL|           0.0|         NULL|      NULL|             NULL|           NULL|          NULL|          NULL|          NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|     NULL|     NULL|         NULL|          NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|          0.0|          0.0|     NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|         NULL|        4349.99|                    0.0|                      1.0|        NULL|              NULL|                NULL|                NULL|        NULL|       NULL|          NULL|                 NULL|       NULL|       NULL|        NULL|        NULL|               NULL|             NULL|         NULL| -1.693131253811575| -1.707628593342747|0.054023112696821585|  NULL| NULL| 4350.774982549938|4352.995028835064| NULL|     NULL|     NULL|          0|     0|       0|        0|        0|    NULL|  66.28206312499998|          NULL|          NULL|
|2017-08-17 16:00:00|4352.33|4354.84|4200.74|4325.23|225.109716|2017-08-17 19:59:...| 965291.09880366|   986|    165.036363|707808.20092154|     0|BTCUSDT| 104.60807722929104|        -253.96297|      NULL|     NULL|-9.009771706166643E9|         NULL| -4.357734674578788|       NULL|      NULL|1017.7724546493212|          NULL|          NULL|          NULL|          NULL|          NULL|            0.0|            0.0|          NULL| 4491.641666666666|4218.236666666667|          NULL| 0.3913364178904299|            0.0|            0.0|          NULL|          NULL|          NULL|          NULL|          NULL|           0.0|         NULL|      NULL|             NULL|           NULL|          NULL|          NULL|          NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|     NULL|     NULL|         NULL|          NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|          0.0|          0.0|     NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|      4333.42|           NULL|                    1.0|                      0.0|        NULL|              NULL|                NULL|                NULL|        NULL|       NULL|          NULL|                 NULL|       NULL|       NULL|        NULL|        NULL|               NULL|             NULL|         NULL| -0.622883322534562|-0.6248313341412626| -0.5691967107970375|  NULL| NULL|4350.5208036190925|4351.906204174865| NULL|     NULL|     NULL|          0|     0|       0|        0|        0|    NULL|-13.779195156250019|          NULL|          NULL|
|2017-08-17 20:00:00|4307.56|4369.69|4258.56|4285.08|249.769913|2017-08-17 23:59:...|1079544.66293121|  1001|    203.226685|878286.96855663|     0|BTCUSDT|-25.951935784027967|       -503.732883|      NULL|     NULL| 1.616651301792292E9|         NULL|-3.7207208761609114|       NULL|      NULL|1017.7724546493212|          NULL|          NULL|          NULL|          NULL|          NULL|            0.0|            0.0|          NULL|          4476.428|         4213.252|          NULL|0.27292762257956527|            0.0|            0.0|          NULL|          NULL|          NULL|          NULL|          NULL|           0.0|         NULL|      NULL|             NULL|           NULL|          NULL|          NULL|          NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|     NULL|     NULL|         NULL|          NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|          0.0|          0.0|     NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|         NULL|        4354.84|                    0.0|                      1.0|        NULL|              NULL|                NULL|                NULL|        NULL|       NULL|          NULL|                 NULL|       NULL|       NULL|        NULL|        NULL|               NULL|             NULL|         NULL|-0.9282743345440547|-0.9326096506869774| -1.4921873383616946|  NULL| NULL| 4349.869651344276|4349.285568717027| NULL|     NULL|     NULL|          0|     0|       0|        0|        0|    NULL| -136.2676171171875|          NULL|          NULL|
+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+------------------+----------+---------+--------------------+-------------+-------------------+-----------+----------+------------------+--------------+--------------+--------------+--------------+--------------+---------------+---------------+--------------+------------------+-----------------+--------------+-------------------+---------------+---------------+--------------+--------------+--------------+--------------+--------------+--------------+-------------+----------+-----------------+---------------+--------------+--------------+--------------+--------------+--------------------+--------------------+---------------------+----------+----------------+---------+---------+-------------+--------------+-------------------+-------------------+----------------+------------------+---------+---------+-------------+-------------+---------+-----------------------+-----------------------+--------------+----------------+---------------+-------------+---------------+-----------------------+-------------------------+------------+------------------+--------------------+--------------------+------------+-----------+--------------+---------------------+-----------+-----------+------------+------------+-------------------+-----------------+-------------+-------------------+-------------------+--------------------+------+-----+------------------+-----------------+-----+---------+---------+-----------+------+--------+---------+---------+--------+-------------------+--------------+--------------+
only showing top 5 rows

In [53]:
df_btc.tail(5)

[Row(open_time=datetime.datetime(2026, 3, 7, 20, 0), open=67080.33, high=67483.05, low=67068.01, close=67262.91, volume=2331.24914, close_time=datetime.datetime(2026, 3, 7, 23, 59, 59, 999000), quote_vol=156958299.280327, trades=298999, taker_buy_base=1271.84113, taker_buy_quote=85618453.7122216, ignore='0', symbol='BTCUSDT', volume_adi=10160549.147140883, volume_obv=2993760.5073450045, volume_cmf=-0.22100979100442159, volume_fi=-824642.7340561997, volume_em=-2663467328.935917, volume_sma_em=-9678680615.837559, volume_vpt=-29.58312465174174, volume_vwap=69207.77214857114, volume_mfi=14.555380609936563, volume_nvi=609985.8576351918, volatility_bbm=70023.889, volatility_bbh=74215.5174290071, volatility_bbl=65832.26057099289, volatility_bbw=11.971995525718675, volatility_bbp=0.170655564208252, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=68230.51733333334, volatility_kch=69068.24233333333, volatility_kcl=67392.79233333333, volatility_kcw=2.4555727634523925, volatility_kcp=-0.07752086504122939, volatility_kchi=0.0, volatility_kcli=1.0, volatility_dcl=66915.26, volatility_dch=74050.0, volatility_dcm=70482.63, volatility_dcw=10.189008496800293, volatility_dcp=0.04872637264988051, volatility_atr=996.3523934931085, volatility_ui=5.893085996990819, trend_macd=-507.7474188811175, trend_macd_signal=-37.27251349598845, trend_macd_diff=-470.47490538512903, trend_sma_fast=68605.76416666666, trend_sma_slow=69960.93807692308, trend_ema_fast=68447.96282840813, trend_ema_slow=68955.71024728924, trend_vortex_ind_pos=0.6668110260212473, trend_vortex_ind_neg=1.4534181072132286, trend_vortex_ind_diff=-0.7866070811919813, trend_trix=0.007991249638153335, trend_mass_index=23.159528087571022, trend_dpo=1056.491000000009, trend_kst=-4.551753774415906, trend_kst_sig=30.394998338484804, trend_kst_diff=-34.94675211290071, trend_ichimoku_conv=68628.51, trend_ichimoku_base=70482.63, trend_ichimoku_a=69555.57, trend_ichimoku_b=68540.0, trend_stc=0.006102776069083436, trend_adx=22.259006102170872, trend_adx_pos=14.177443196793702, trend_adx_neg=27.273622597188798, trend_cci=-98.69179272265386, trend_visual_ichimoku_a=67120.30249999999, trend_visual_ichimoku_b=66303.14, trend_aroon_up=24.0, trend_aroon_down=96.0, trend_aroon_ind=-72.0, trend_psar_up=None, trend_psar_down=71815.202017991, trend_psar_up_indicator=0.0, trend_psar_down_indicator=0.0, momentum_rsi=37.723594728804365, momentum_stoch_rsi=0.07881838209359483, momentum_stoch_rsi_k=0.0330302947749359, momentum_stoch_rsi_d=0.025991410108651174, momentum_tsi=-11.19757937689244, momentum_uo=40.1820878021437, momentum_stoch=7.335332184099826, momentum_stoch_signal=5.691012219143819, momentum_wr=-92.66466781590017, momentum_ao=-1814.6546176470729, momentum_roc=-5.117468125588226, momentum_ppo=-20.3013361639071, momentum_ppo_signal=-14.24283468956936, momentum_ppo_hist=-6.058501474337739, momentum_kama=67600.94852579494, others_dr=0.2721661816263987, others_dlr=0.2717964801238537, others_cr=1446.277347764018, sma200=68586.22925, sma50=68380.0512, ema200=70937.96938300143, ema50=68663.3056311901, slope=-38.87208876399055, slope_obv=-1852.6729630303469, slope_rsi=-1.0339849979804403, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=40.27881971517645, obv_ema7=2996448.2102077045, slope_rsi_ema7=-1.6982459270425565, slope_obv_ema7=-2317.6377156921676),
 Row(open_time=datetime.datetime(2026, 3, 8, 0, 0), open=67262.91, high=67481.96, low=66833.58, close=67000.26, volume=2883.43952, close_time=datetime.datetime(2026, 3, 8, 3, 59, 59, 999000), quote_vol=193604407.914392, trades=392656, taker_buy_base=1489.32538, taker_buy_quote=99998828.4028834, ignore='0', symbol='BTCUSDT', volume_adi=10159148.20769551, volume_obv=2990877.0678250045, volume_cmf=-0.31279360102025966, volume_fi=-815027.3991807462, volume_em=-2647991340.563895, volume_sma_em=-8251018785.005692, volume_vpt=-4.914459561732123, volume_vwap=68865.49601734533, volume_mfi=15.13329748303704, volume_nvi=609985.8576351918, volatility_bbm=69693.34700000001, volatility_bbh=73741.50296858992, volatility_bbl=65645.1910314101, volatility_bbw=11.617051391117467, volatility_bbp=0.167368670958336, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=67892.226, volatility_kch=68706.432, volatility_kcl=67078.02, volatility_kcw=2.398524979870297, volatility_kcp=-0.04775204309475088, volatility_kchi=0.0, volatility_kcli=1.0, volatility_dcl=66833.58, volatility_dch=73716.0, volatility_dcm=70274.79000000001, volatility_dcw=9.875289817835837, volatility_dcp=0.024218225566006297, volatility_atr=961.5551541437981, volatility_ui=6.0104877847390705, trend_macd=-585.6227644780447, trend_macd_signal=-146.9425636923997, trend_macd_diff=-438.680200785645, trend_sma_fast=68265.75416666667, trend_sma_slow=69905.75576923076, trend_ema_fast=68225.23931634534, trend_ema_slow=68810.86208082338, trend_vortex_ind_pos=0.6809185992491493, trend_vortex_ind_neg=1.349282841346173, trend_vortex_ind_diff=-0.6683642420970237, trend_trix=-0.017271353822339398, trend_mass_index=22.991541416486253, trend_dpo=1363.0929999999935, trend_kst=-13.232978901801523, trend_kst_sig=22.229303453266308, trend_kst_diff=-35.46228235506783, trend_ichimoku_conv=67814.51000000001, trend_ichimoku_base=70441.79000000001, trend_ichimoku_a=69128.15000000001, trend_ichimoku_b=68540.0, trend_stc=0.003051388034541718, trend_adx=23.110613866464366, trend_adx_pos=13.566093932440454, trend_adx_neg=27.656653420943915, trend_cci=-94.22066942355136, trend_visual_ichimoku_a=67120.30249999999, trend_visual_ichimoku_b=66303.14, trend_aroon_up=20.0, trend_aroon_down=100.0, trend_aroon_ind=-80.0, trend_psar_up=None, trend_psar_down=71423.20665655172, trend_psar_up_indicator=0.0, trend_psar_down_indicator=0.0, momentum_rsi=36.33859257766426, momentum_stoch_rsi=0.009318008479581167, momentum_stoch_rsi_k=0.029378796857724748, momentum_stoch_rsi_d=0.028293686469389175, momentum_tsi=-13.424301189134368, momentum_uo=38.103090393917405, momentum_stoch=3.51740554411303, momentum_stoch_signal=4.512595388594632, momentum_wr=-96.48259445588697, momentum_ao=-1971.0463823529426, momentum_roc=-5.740149391435456, momentum_ppo=-19.264765549483258, momentum_ppo_signal=-15.24722086155214, momentum_ppo_hist=-4.017544687931117, momentum_kama=67413.2705343028, others_dr=-0.3904826597600497, others_dlr=-0.3912470337786189, others_cr=1440.239402849202, sma200=68529.52305, sma50=68412.21280000001, ema200=70898.78819511087, ema50=68598.08815545717, slope=-43.355398414361844, slope_obv=-1306.199680727426, slope_rsi=-0.6438350056275569, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=39.29376293079841, obv_ema7=2995055.4246120295, slope_rsi_ema7=-1.4346431966888082, slope_obv_ema7=-2064.778206951217),
 Row(open_time=datetime.datetime(2026, 3, 8, 4, 0), open=67000.26, high=67465.11, low=66547.15, close=67319.91, volume=2866.09804, close_time=datetime.datetime(2026, 3, 8, 7, 59, 59, 999000), quote_vol=192314275.5770752, trades=406105, taker_buy_base=1502.2707, taker_buy_quote=100825792.9239443, ignore='0', symbol='BTCUSDT', volume_adi=10161107.605148539, volume_obv=2993743.1658650045, volume_cmf=-0.26026191203834037, volume_fi=-567716.593799779, volume_em=-4856758298.4707365, volume_sma_em=-8645363748.836695, volume_vpt=2.4144699129808593, volume_vwap=68584.4444882685, volume_mfi=14.622074610829458, volume_nvi=612896.0251389162, volatility_bbm=69426.004, volatility_bbh=73357.9334752886, volatility_bbl=65494.074524711395, volatility_bbw=11.326964678216552, volatility_bbp=0.23218059819785944, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=67702.53366666667, volatility_kch=68392.00666666667, volatility_kcl=67013.06066666667, volatility_kcw=2.0367716321950886, volatility_kcp=0.22252454652563086, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=66547.15, volatility_dch=73558.15, volatility_dcm=70052.65, volatility_dcw=10.098521585658307, volatility_dcp=0.11022108115818133, volatility_atr=957.1956387294189, volatility_ui=6.095049385357128, trend_macd=-614.4633028861426, trend_macd_signal=-240.44671153114828, trend_macd_diff=-374.0165913549944, trend_sma_fast=67954.37666666666, trend_sma_slow=69866.59846153847, trend_ema_fast=68085.95788306143, trend_ema_slow=68700.42118594758, trend_vortex_ind_pos=0.6495309099013924, trend_vortex_ind_neg=1.3403059546230005, trend_vortex_ind_diff=-0.6907750447216081, trend_trix=-0.039578008849228685, trend_mass_index=22.87724845282626, trend_dpo=786.9459999999963, trend_kst=-18.593900253154104, trend_kst_sig=14.034109719940636, trend_kst_diff=-32.62800997309474, trend_ichimoku_conv=67549.095, trend_ichimoku_base=70298.575, trend_ichimoku_a=68923.83499999999, trend_ichimoku_b=68540.0, trend_stc=0.001525694017270859, trend_adx=24.12426459431961, trend_adx_pos=12.729198192701702, trend_adx_neg=27.875421316006527, trend_cci=-86.14926547587784, trend_visual_ichimoku_a=67120.30249999999, trend_visual_ichimoku_b=66303.14, trend_aroon_up=16.0, trend_aroon_down=96.0, trend_aroon_ind=-80.0, trend_psar_up=None, trend_psar_down=70964.24399089655, trend_psar_up_indicator=0.0, trend_psar_down_indicator=0.0, momentum_rsi=39.26129688179603, momentum_stoch_rsi=0.15598134826806595, momentum_stoch_rsi_k=0.08137257961374673, momentum_stoch_rsi_d=0.04792722374880117, momentum_tsi=-14.613397121917938, momentum_uo=46.55972988618787, momentum_stoch=15.858546265722568, momentum_stoch_signal=8.903761331311761, momentum_wr=-84.14145373427743, momentum_ao=-2152.429352941166, momentum_roc=-5.258538142355568, momentum_ppo=-18.294777668017666, momentum_ppo_signal=-15.856732222845247, momentum_ppo_hist=-2.4380454451724187, momentum_kama=67402.01724134549, others_dr=0.47708770085370666, others_dlr=0.47595324428630903, others_cr=1447.587695603898, sma200=68472.42955, sma50=68441.16900000001, ema200=70863.17746680131, ema50=68547.96352190983, slope=-46.809254448023246, slope_obv=-906.6683497576818, slope_rsi=-0.46856489242556326, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=39.28564641854781, obv_ema7=2994727.359925273, slope_rsi_ema7=-1.1931236206229958, slope_obv_ema7=-1775.2507426528332),
 Row(open_time=datetime.datetime(2026, 3, 8, 8, 0), open=67319.9, high=68200.0, low=67156.93, close=67515.0, volume=3303.40428, close_time=datetime.datetime(2026, 3, 8, 11, 59, 59, 999000), quote_vol=223403298.97890967, trades=483848, taker_buy_base=1909.2687, taker_buy_quote=129104579.0869395, ignore='0', symbol='BTCUSDT', volume_adi=10160072.217340184, volume_obv=2997046.5701450044, volume_cmf=-0.24409760702944966, volume_fi=-394548.34597335506, volume_em=21229386687.420643, volume_sma_em=-6387181065.349442, volume_vpt=23.246914769176286, volume_vwap=68334.52331445132, volume_mfi=22.48116256918206, volume_nvi=612896.0251389162, volatility_bbm=69176.85949999999, volatility_bbh=72925.84176313854, volatility_bbl=65427.87723686144, volatility_bbw=10.83883336201046, volatility_bbp=0.2783585806286634, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=67642.53099999999, volatility_kch=68331.24500000001, volatility_kcl=66953.817, volatility_kcw=2.036334211089787, volatility_kcp=0.40741367243877624, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=66547.15, volatility_dch=73558.15, volatility_dcm=70052.65, volatility_dcw=10.134892000987701, volatility_dcp=0.13804735415775293, volatility_atr=965.7830748564777, volatility_ui=6.1708721591144915, trend_macd=-614.494000466424, trend_macd_signal=-315.25616931820343, trend_macd_diff=-299.2378311482206, trend_sma_fast=67729.5475, trend_sma_slow=69858.24461538462, trend_ema_fast=67998.1182087443, trend_ema_slow=68612.61220921073, trend_vortex_ind_pos=0.7352077851619649, trend_vortex_ind_neg=1.2675239672222942, trend_vortex_ind_diff=-0.5323161820603293, trend_trix=-0.05833608533816269, trend_mass_index=22.755170695916004, trend_dpo=-672.149499999985, trend_kst=-22.564882101784907, trend_kst_sig=6.139840601396683, trend_kst_diff=-28.704722703181588, trend_ichimoku_conv=67549.095, trend_ichimoku_base=70298.575, trend_ichimoku_a=68923.83499999999, trend_ichimoku_b=68540.0, trend_stc=0.0007628470086354295, trend_adx=23.92967697227746, trend_adx_pos=16.78102456604587, trend_adx_neg=25.918804071655536, trend_cci=-62.49292827652561, trend_visual_ichimoku_a=67345.0, trend_visual_ichimoku_b=66303.14, trend_aroon_up=12.0, trend_aroon_down=92.0, trend_aroon_ind=-80.0, trend_psar_up=None, trend_psar_down=70434.19271198896, trend_psar_up_indicator=0.0, trend_psar_down_indicator=0.0, momentum_rsi=41.04042797254393, momentum_stoch_rsi=0.24704638009629937, momentum_stoch_rsi_k=0.13744857894798157, momentum_stoch_rsi_d=0.08273331847314973, momentum_tsi=-15.181313423907397, momentum_uo=43.24612685095151, momentum_stoch=20.83364724976926, momentum_stoch_signal=13.403199686534904, momentum_wr=-79.16635275023074, momentum_ao=-2137.4676764705946, momentum_roc=-3.8425247764123247, momentum_ppo=-16.2060632601689, momentum_ppo_signal=-15.92659843030998, momentum_ppo_hist=-0.2794648298589202, momentum_kama=67407.62680813124, others_dr=0.2897953963396427, others_dlr=0.289376298969124, others_cr=1452.072533500077, sma200=68416.23795, sma50=68475.5206, ema200=70829.86226812667, ema50=68507.4551485016, slope=-49.26849224150483, slope_obv=-419.9927524849743, slope_rsi=-0.25930150191728035, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=39.72434180704684, obv_ema7=2995307.1624802053, slope_rsi_ema7=-0.9596680909465636, slope_obv_ema7=-1436.436245110882),
 Row(open_time=datetime.datetime(2026, 3, 8, 12, 0), open=67515.0, high=67650.94, low=66761.68, close=67341.72, volume=3787.4199, close_time=datetime.datetime(2026, 3, 8, 15, 59, 59, 999000), quote_vol=254254565.4022346, trades=458356, taker_buy_base=1892.62118, taker_buy_quote=127055724.2549012, ignore='0', symbol='BTCUSDT', volume_adi=10161225.658467997, volume_obv=2993259.1502450043, volume_cmf=-0.19330951497949742, volume_fi=-431939.1708731608, volume_em=-11085872873.509573, volume_sma_em=-6659467600.2355795, volume_vpt=-0.14745405567702008, volume_vwap=68056.21295809193, volume_mfi=22.19797929908229, volume_nvi=612896.0251389162, volatility_bbm=68941.1705, volatility_bbh=72525.70728481453, volatility_bbl=65356.63371518545, volatility_bbw=10.398827750725642, volatility_bbp=0.2768957893282234, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=67556.611, volatility_kch=68267.859, volatility_kcl=66845.36299999998, volatility_kcw=2.105635523960806, volatility_kcp=0.3489338458596814, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=66547.15, volatility_dch=73558.15, volatility_dcm=70052.65, volatility_dcw=10.169540129870585, volatility_dcp=0.11333190700328155, volatility_atr=958.1307673708309, volatility_ui=6.197888763060436, trend_macd=-621.3381766280072, trend_macd_signal=-376.47257078016423, trend_macd_diff=-244.86560584784297, trend_sma_fast=67632.63166666667, trend_sma_slow=69775.49807692308, trend_ema_fast=67897.13386893748, trend_ema_slow=68518.47204556549, trend_vortex_ind_pos=0.7152633227573104, trend_vortex_ind_neg=1.2982354209189675, trend_vortex_ind_diff=-0.5829720981616571, trend_trix=-0.07429804462133618, trend_mass_index=22.551340114740096, trend_dpo=-809.3804999999993, trend_kst=-26.03953299367002, trend_kst_sig=-1.1104962327393066, trend_kst_diff=-24.92903676093071, trend_ichimoku_conv=67389.70999999999, trend_ichimoku_base=70298.575, trend_ichimoku_a=68844.14249999999, trend_ichimoku_b=68540.0, trend_stc=0.00038142350431771474, trend_adx=24.101926292955223, trend_adx_pos=15.765056726140475, trend_adx_neg=27.040554448751173, trend_cci=-72.4071445492131, trend_visual_ichimoku_a=67238.0, trend_visual_ichimoku_b=66303.14, trend_aroon_up=8.0, trend_aroon_down=88.0, trend_aroon_ind=-80.0, trend_psar_up=None, trend_psar_down=69967.74758655028, trend_psar_up_indicator=0.0, trend_psar_down_indicator=0.0, momentum_rsi=39.92188772074508, momentum_stoch_rsi=0.25443470915674576, momentum_stoch_rsi_k=0.21915414584036977, momentum_stoch_rsi_d=0.1459917681340314, momentum_tsi=-15.952957306147523, momentum_uo=43.96982093654825, momentum_stoch=17.577310123152127, momentum_stoch_signal=18.089834546214604, momentum_wr=-82.42268987684787, momentum_ao=-2126.6437058823503, momentum_roc=-1.697678889524538, momentum_ppo=-13.157242481253279, momentum_ppo_signal=-15.37272724049864, momentum_ppo_hist=2.2154847592453617, momentum_kama=67403.49399516112, others_dr=-0.2566540768718095, others_dlr=-0.2569839980727906, others_cr=1448.0890760668417, sma200=68358.97320000001, sma50=68545.835, ema200=70795.15438486173, ema50=68461.74004463879, slope=-50.89604037701787, slope_obv=-237.635728060675, slope_rsi=-0.11521686208850031, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=39.7737282854714, obv_ema7=2994795.159421405, slope_rsi_ema7=-0.7485552837320475, slope_obv_ema7=-1136.7361158483304)]

In [54]:
# Mostrar as colunas de open_time e preço de fecho
df_btc[['open_time','close']].show(10)

+-------------------+-------+
|          open_time|  close|
+-------------------+-------+
|2017-08-17 04:00:00|4349.99|
|2017-08-17 08:00:00| 4427.3|
|2017-08-17 12:00:00|4352.34|
|2017-08-17 16:00:00|4325.23|
|2017-08-17 20:00:00|4285.08|
|2017-08-18 00:00:00|4292.39|
|2017-08-18 04:00:00|4300.25|
|2017-08-18 08:00:00|4340.31|
|2017-08-18 12:00:00|4236.89|
|2017-08-18 16:00:00|4136.28|
+-------------------+-------+
only showing top 10 rows

In [55]:
df_btc.take(4)

[Row(open_time=datetime.datetime(2017, 8, 17, 4, 0), open=4261.48, high=4349.99, low=4261.32, close=4349.99, volume=82.088865, close_time=datetime.datetime(2017, 8, 17, 7, 59, 59, 999000), quote_vol=353194.33293028, trades=334, taker_buy_base=64.013727, taker_buy_quote=275647.42191079, ignore='0', symbol='BTCUSDT', volume_adi=82.088865, volume_obv=82.088865, volume_cmf=None, volume_fi=None, volume_em=None, volume_sma_em=None, volume_vpt=-71.42359467918801, volume_vwap=None, volume_mfi=None, volume_nvi=1000.0, volatility_bbm=None, volatility_bbh=None, volatility_bbl=None, volatility_bbw=None, volatility_bbp=None, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=None, volatility_kch=4409.1033333333335, volatility_kcl=4231.763333333333, volatility_kcw=None, volatility_kcp=0.666666666666665, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=None, volatility_dch=None, volatility_dcm=None, volatility_dcw=None, volatility_dcp=None, volatility_atr=0.0, volatility_ui=None, trend_macd=None, trend_macd_signal=None, trend_macd_diff=None, trend_sma_fast=None, trend_sma_slow=None, trend_ema_fast=None, trend_ema_slow=None, trend_vortex_ind_pos=None, trend_vortex_ind_neg=None, trend_vortex_ind_diff=None, trend_trix=None, trend_mass_index=None, trend_dpo=None, trend_kst=None, trend_kst_sig=None, trend_kst_diff=None, trend_ichimoku_conv=None, trend_ichimoku_base=None, trend_ichimoku_a=None, trend_ichimoku_b=4305.655, trend_stc=None, trend_adx=0.0, trend_adx_pos=0.0, trend_adx_neg=0.0, trend_cci=None, trend_visual_ichimoku_a=36800.77023033349, trend_visual_ichimoku_b=36650.080737310906, trend_aroon_up=None, trend_aroon_down=None, trend_aroon_ind=None, trend_psar_up=None, trend_psar_down=None, trend_psar_up_indicator=0.0, trend_psar_down_indicator=0.0, momentum_rsi=None, momentum_stoch_rsi=None, momentum_stoch_rsi_k=None, momentum_stoch_rsi_d=None, momentum_tsi=None, momentum_uo=None, momentum_stoch=None, momentum_stoch_signal=None, momentum_wr=None, momentum_ao=None, momentum_roc=None, momentum_ppo=None, momentum_ppo_signal=None, momentum_ppo_hist=None, momentum_kama=None, others_dr=-88.19698946294015, others_dlr=None, others_cr=0.0, sma200=None, sma50=None, ema200=4349.99, ema50=4349.99, slope=None, slope_obv=None, slope_rsi=None, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=None, obv_ema7=82.088865, slope_rsi_ema7=None, slope_obv_ema7=None),
 Row(open_time=datetime.datetime(2017, 8, 17, 8, 0), open=4333.32, high=4485.39, low=4333.32, close=4427.3, volume=63.619882, close_time=datetime.datetime(2017, 8, 17, 11, 59, 59, 999000), quote_vol=282501.15774965, trades=248, taker_buy_base=58.787633, taker_buy_quote=261054.05115395, ignore='0', symbol='BTCUSDT', volume_adi=97.10377632360104, volume_obv=145.708747, volume_cmf=None, volume_fi=None, volume_em=24787312557.41736, volume_sma_em=None, volume_vpt=-71.269226146657, volume_vwap=None, volume_mfi=None, volume_nvi=1017.7724546493212, volatility_bbm=None, volatility_bbh=None, volatility_bbl=None, volatility_bbw=None, volatility_bbp=None, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=None, volatility_kch=4488.255, volatility_kcl=4247.514999999999, volatility_kcw=None, volatility_kcp=0.7468015286200891, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=None, volatility_dch=None, volatility_dcm=None, volatility_dcw=None, volatility_dcp=None, volatility_atr=0.0, volatility_ui=None, trend_macd=None, trend_macd_signal=None, trend_macd_diff=None, trend_sma_fast=None, trend_sma_slow=None, trend_ema_fast=None, trend_ema_slow=None, trend_vortex_ind_pos=None, trend_vortex_ind_neg=None, trend_vortex_ind_diff=None, trend_trix=None, trend_mass_index=None, trend_dpo=None, trend_kst=None, trend_kst_sig=None, trend_kst_diff=None, trend_ichimoku_conv=None, trend_ichimoku_base=None, trend_ichimoku_a=None, trend_ichimoku_b=4373.355, trend_stc=None, trend_adx=0.0, trend_adx_pos=0.0, trend_adx_neg=0.0, trend_cci=None, trend_visual_ichimoku_a=36800.77023033349, trend_visual_ichimoku_b=36650.080737310906, trend_aroon_up=None, trend_aroon_down=None, trend_aroon_ind=None, trend_psar_up=None, trend_psar_down=None, trend_psar_up_indicator=0.0, trend_psar_down_indicator=0.0, momentum_rsi=None, momentum_stoch_rsi=None, momentum_stoch_rsi_k=None, momentum_stoch_rsi_d=None, momentum_tsi=None, momentum_uo=None, momentum_stoch=None, momentum_stoch_signal=None, momentum_wr=None, momentum_ao=None, momentum_roc=None, momentum_ppo=None, momentum_ppo_signal=None, momentum_ppo_hist=None, momentum_kama=None, others_dr=1.77724546493212, others_dlr=1.761637118809567, others_cr=1.77724546493212, sma200=None, sma50=None, ema200=4350.759253731344, ema50=4353.021764705883, slope=None, slope_obv=None, slope_rsi=None, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=None, obv_ema7=97.99383549999999, slope_rsi_ema7=None, slope_obv_ema7=None),
 Row(open_time=datetime.datetime(2017, 8, 17, 12, 0), open=4436.06, high=4485.39, low=4333.42, close=4352.34, volume=174.562001, close_time=datetime.datetime(2017, 8, 17, 15, 59, 59, 999000), quote_vol=774238.79831726, trades=858, taker_buy_base=125.184133, taker_buy_quote=555419.7580611, ignore='0', symbol='BTCUSDT', volume_adi=-33.99289521768992, volume_obv=-28.85325400000002, volume_cmf=None, volume_fi=None, volume_em=4352894.648605486, volume_sma_em=None, volume_vpt=-1.8248823285697195, volume_vwap=None, volume_mfi=None, volume_nvi=1017.7724546493212, volatility_bbm=None, volatility_bbh=None, volatility_bbl=None, volatility_bbw=None, volatility_bbp=None, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=None, volatility_kch=4506.2877777777785, volatility_kcl=4244.481111111111, volatility_kcw=None, volatility_kcp=0.41197915340412267, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=None, volatility_dch=None, volatility_dcm=None, volatility_dcw=None, volatility_dcp=None, volatility_atr=0.0, volatility_ui=None, trend_macd=None, trend_macd_signal=None, trend_macd_diff=None, trend_sma_fast=None, trend_sma_slow=None, trend_ema_fast=None, trend_ema_slow=None, trend_vortex_ind_pos=None, trend_vortex_ind_neg=None, trend_vortex_ind_diff=None, trend_trix=None, trend_mass_index=None, trend_dpo=None, trend_kst=None, trend_kst_sig=None, trend_kst_diff=None, trend_ichimoku_conv=None, trend_ichimoku_base=None, trend_ichimoku_a=None, trend_ichimoku_b=4373.355, trend_stc=None, trend_adx=0.0, trend_adx_pos=0.0, trend_adx_neg=0.0, trend_cci=None, trend_visual_ichimoku_a=36800.77023033349, trend_visual_ichimoku_b=36650.080737310906, trend_aroon_up=None, trend_aroon_down=None, trend_aroon_ind=None, trend_psar_up=None, trend_psar_down=4349.99, trend_psar_up_indicator=0.0, trend_psar_down_indicator=1.0, momentum_rsi=None, momentum_stoch_rsi=None, momentum_stoch_rsi_k=None, momentum_stoch_rsi_d=None, momentum_tsi=None, momentum_uo=None, momentum_stoch=None, momentum_stoch_signal=None, momentum_wr=None, momentum_ao=None, momentum_roc=None, momentum_ppo=None, momentum_ppo_signal=None, momentum_ppo_hist=None, momentum_kama=None, others_dr=-1.693131253811575, others_dlr=-1.707628593342747, others_cr=0.054023112696821585, sma200=None, sma50=None, ema200=4350.774982549938, ema50=4352.995028835064, slope=None, slope_obv=None, slope_rsi=None, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=None, obv_ema7=66.28206312499998, slope_rsi_ema7=None, slope_obv_ema7=None),
 Row(open_time=datetime.datetime(2017, 8, 17, 16, 0), open=4352.33, high=4354.84, low=4200.74, close=4325.23, volume=225.109716, close_time=datetime.datetime(2017, 8, 17, 19, 59, 59, 999000), quote_vol=965291.09880366, trades=986, taker_buy_base=165.036363, taker_buy_quote=707808.20092154, ignore='0', symbol='BTCUSDT', volume_adi=104.60807722929104, volume_obv=-253.96297, volume_cmf=None, volume_fi=None, volume_em=-9009771706.166643, volume_sma_em=None, volume_vpt=-4.357734674578788, volume_vwap=None, volume_mfi=None, volume_nvi=1017.7724546493212, volatility_bbm=None, volatility_bbh=None, volatility_bbl=None, volatility_bbw=None, volatility_bbp=None, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=None, volatility_kch=4491.641666666666, volatility_kcl=4218.236666666667, volatility_kcw=None, volatility_kcp=0.3913364178904299, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=None, volatility_dch=None, volatility_dcm=None, volatility_dcw=None, volatility_dcp=None, volatility_atr=0.0, volatility_ui=None, trend_macd=None, trend_macd_signal=None, trend_macd_diff=None, trend_sma_fast=None, trend_sma_slow=None, trend_ema_fast=None, trend_ema_slow=None, trend_vortex_ind_pos=None, trend_vortex_ind_neg=None, trend_vortex_ind_diff=None, trend_trix=None, trend_mass_index=None, trend_dpo=None, trend_kst=None, trend_kst_sig=None, trend_kst_diff=None, trend_ichimoku_conv=None, trend_ichimoku_base=None, trend_ichimoku_a=None, trend_ichimoku_b=4343.0650000000005, trend_stc=None, trend_adx=0.0, trend_adx_pos=0.0, trend_adx_neg=0.0, trend_cci=None, trend_visual_ichimoku_a=36800.77023033349, trend_visual_ichimoku_b=36650.080737310906, trend_aroon_up=None, trend_aroon_down=None, trend_aroon_ind=None, trend_psar_up=4333.42, trend_psar_down=None, trend_psar_up_indicator=1.0, trend_psar_down_indicator=0.0, momentum_rsi=None, momentum_stoch_rsi=None, momentum_stoch_rsi_k=None, momentum_stoch_rsi_d=None, momentum_tsi=None, momentum_uo=None, momentum_stoch=None, momentum_stoch_signal=None, momentum_wr=None, momentum_ao=None, momentum_roc=None, momentum_ppo=None, momentum_ppo_signal=None, momentum_ppo_hist=None, momentum_kama=None, others_dr=-0.622883322534562, others_dlr=-0.6248313341412626, others_cr=-0.5691967107970375, sma200=None, sma50=None, ema200=4350.5208036190925, ema50=4351.906204174865, slope=None, slope_obv=None, slope_rsi=None, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=None, obv_ema7=-13.779195156250019, slope_rsi_ema7=None, slope_obv_ema7=None)]

In [56]:
df_btc.describe().toPandas()

26/05/08 18:26:17 WARN DAGScheduler: Broadcasting large task binary with size 1343.5 KiB

,summary,open,high,low,close,volume,quote_vol,trades,taker_buy_base,taker_buy_quote,...,slope_rsi,morningstar,hammer,piercing,3soldiers,engulfing,rsi_ema7,obv_ema7,slope_rsi_ema7,slope_obv_ema7
0,count,18737,18737,18737,18737,18737,18737,18737,18737,18737,...,18715,18737,18737,18737,18737,18737,18724,18737,18715,18728
1,mean,36851.50620643648,37158.71899770507,36522.64440038424,36854.919228798644,10285.335104555536,2.9448541997345865E8,324452.4468698297,5107.098767987176,1.4534167441448164E8,...,-2.363287042217809E-6,0.25617761648076,2.8713241180551847,0.0,0.0160111010300475,0.4536478625180125,51.23981376526117,1436217.1842401233,5.703099177658923E-4,160.03452454278195
2,stddev,32392.4105006488,32593.654888546018,32177.907027676054,32392.274918945255,14209.96097336185,3.672436551540139E8,417270.04843629216,7075.550803575971,1.8248016760612002E8,...,1.4955637501531103,5.055046832197454,16.70038307197394,0.0,1.2652822571712152,27.28278079175645,11.84921090620574,1408075.2077735618,1.116009722214783,5278.237856063056
3,min,2870.9,3148.0,2817.0,2919.0,0.0,0.0,0,0.0,0.0,...,-6.59714417413364,0,0,0,0,-100,9.434183659008966,-876240.6746982055,-5.0027796215811975,-91121.04667906821
4,max,125410.8,126199.63,124800.0,125410.81,284711.694213,5.45762388223572E9,6089593,141232.701595,2.7475369760882463E9,...,8.101798827505222,100,100,0,100,100,88.81457874325532,3396602.5579327107,5.83359439063099,57083.397617638635

In [57]:
df_btc.take(1)

[Row(open_time=datetime.datetime(2017, 8, 17, 4, 0), open=4261.48, high=4349.99, low=4261.32, close=4349.99, volume=82.088865, close_time=datetime.datetime(2017, 8, 17, 7, 59, 59, 999000), quote_vol=353194.33293028, trades=334, taker_buy_base=64.013727, taker_buy_quote=275647.42191079, ignore='0', symbol='BTCUSDT', volume_adi=82.088865, volume_obv=82.088865, volume_cmf=None, volume_fi=None, volume_em=None, volume_sma_em=None, volume_vpt=-71.42359467918801, volume_vwap=None, volume_mfi=None, volume_nvi=1000.0, volatility_bbm=None, volatility_bbh=None, volatility_bbl=None, volatility_bbw=None, volatility_bbp=None, volatility_bbhi=0.0, volatility_bbli=0.0, volatility_kcc=None, volatility_kch=4409.1033333333335, volatility_kcl=4231.763333333333, volatility_kcw=None, volatility_kcp=0.666666666666665, volatility_kchi=0.0, volatility_kcli=0.0, volatility_dcl=None, volatility_dch=None, volatility_dcm=None, volatility_dcw=None, volatility_dcp=None, volatility_atr=0.0, volatility_ui=None, trend_macd=None, trend_macd_signal=None, trend_macd_diff=None, trend_sma_fast=None, trend_sma_slow=None, trend_ema_fast=None, trend_ema_slow=None, trend_vortex_ind_pos=None, trend_vortex_ind_neg=None, trend_vortex_ind_diff=None, trend_trix=None, trend_mass_index=None, trend_dpo=None, trend_kst=None, trend_kst_sig=None, trend_kst_diff=None, trend_ichimoku_conv=None, trend_ichimoku_base=None, trend_ichimoku_a=None, trend_ichimoku_b=4305.655, trend_stc=None, trend_adx=0.0, trend_adx_pos=0.0, trend_adx_neg=0.0, trend_cci=None, trend_visual_ichimoku_a=36800.77023033349, trend_visual_ichimoku_b=36650.080737310906, trend_aroon_up=None, trend_aroon_down=None, trend_aroon_ind=None, trend_psar_up=None, trend_psar_down=None, trend_psar_up_indicator=0.0, trend_psar_down_indicator=0.0, momentum_rsi=None, momentum_stoch_rsi=None, momentum_stoch_rsi_k=None, momentum_stoch_rsi_d=None, momentum_tsi=None, momentum_uo=None, momentum_stoch=None, momentum_stoch_signal=None, momentum_wr=None, momentum_ao=None, momentum_roc=None, momentum_ppo=None, momentum_ppo_signal=None, momentum_ppo_hist=None, momentum_kama=None, others_dr=-88.19698946294015, others_dlr=None, others_cr=0.0, sma200=None, sma50=None, ema200=4349.99, ema50=4349.99, slope=None, slope_obv=None, slope_rsi=None, morningstar=0, hammer=0, piercing=0, 3soldiers=0, engulfing=0, rsi_ema7=None, obv_ema7=82.088865, slope_rsi_ema7=None, slope_obv_ema7=None)]

In [58]:
df_btc.explain()

== Physical Plan ==
FileScan parquet [open_time#6870,open#6871,high#6872,low#6873,close#6874,volume#6875,close_time#6876,quote_vol#6877,trades#6878L,taker_buy_base#6879,taker_buy_quote#6880,ignore#6881,symbol#6882,volume_adi#6883,volume_obv#6884,volume_cmf#6885,volume_fi#6886,volume_em#6887,volume_sma_em#6888,volume_vpt#6889,volume_vwap#6890,volume_mfi#6891,volume_nvi#6892,volatility_bbm#6893,volatility_bbh#6894,... 87 more fields] Batched: false, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/home/sobreiro/git/teaching/big_data/data/btc_04h_usdt_binance.pa..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<open_time:timestamp_ntz,open:double,high:double,low:double,close:double,volume:double,clos...

# Exemplo com pyspark.pandas

Advantages of pyspark.pandas over pandas:

* Scalability: The biggest advantage is its ability to handle datasets that are far too large to fit into the memory of a single machine. pyspark.pandas leverages the power of Apache Spark to distribute data and computations across a cluster of machines, enabling processing of massive datasets that would overwhelm pandas.
* Distributed Computing: By distributing workloads, pyspark.pandas can often achieve significantly faster processing times than pandas on large datasets. This is especially beneficial for tasks like complex aggregations, joins, or machine learning algorithms.
* Integration with Spark Ecosystem: pyspark.pandas seamlessly integrates with other components of the Spark ecosystem, such as Spark SQL for querying structured data, Spark Streaming for real-time processing, and MLlib for machine learning. This makes it easier to build end-to-end big data pipelines.
* Familiarity: The API of pyspark.pandas is intentionally designed to be very similar to pandas, making it easier for data scientists familiar with pandas to transition to big data analysis.
* pyspark.pandas: The preferred choice for large-scale datasets that exceed the memory capacity of a single machine. It provides scalability, distributed computing capabilities, and integration with the broader Spark ecosystem.

In [62]:
#import pyspark.pandas as ps
#df_btc_pandas = ps.DataFrame(df_btc)
# da incompabilidade entre as versões do PySpark, a funcionalidade de pandas API no PySpark não está disponível. 
# Portanto, não é possível converter diretamente o DataFrame do Spark para um DataFrame do pandas usando a API de pandas do PySpark.

df_btc_pandas = df_btc.toPandas()

In [63]:
df_btc_pandas.head()

,open_time,open,high,low,close,volume,close_time,quote_vol,trades,taker_buy_base,...,slope_rsi,morningstar,hammer,piercing,3soldiers,engulfing,rsi_ema7,obv_ema7,slope_rsi_ema7,slope_obv_ema7
0,2017-08-17 04:00:00,4261.48,4349.99,4261.32,4349.99,82.088865,2017-08-17 07:59:59.999,3.531943e+05,334,64.013727,...,NaN,0,0,0,0,0,NaN,82.088865,NaN,NaN
1,2017-08-17 08:00:00,4333.32,4485.39,4333.32,4427.30,63.619882,2017-08-17 11:59:59.999,2.825012e+05,248,58.787633,...,NaN,0,0,0,0,0,NaN,97.993835,NaN,NaN
2,2017-08-17 12:00:00,4436.06,4485.39,4333.42,4352.34,174.562001,2017-08-17 15:59:59.999,7.742388e+05,858,125.184133,...,NaN,0,0,0,0,0,NaN,66.282063,NaN,NaN
3,2017-08-17 16:00:00,4352.33,4354.84,4200.74,4325.23,225.109716,2017-08-17 19:59:59.999,9.652911e+05,986,165.036363,...,NaN,0,0,0,0,0,NaN,-13.779195,NaN,NaN
4,2017-08-17 20:00:00,4307.56,4369.69,4258.56,4285.08,249.769913,2017-08-17 23:59:59.999,1.079545e+06,1001,203.226685,...,NaN,0,0,0,0,0,NaN,-136.267617,NaN,NaN

In [64]:
df_btc_pandas.describe()

,open_time,open,high,low,close,volume,close_time,quote_vol,trades,taker_buy_base,...,slope_rsi,morningstar,hammer,piercing,3soldiers,engulfing,rsi_ema7,obv_ema7,slope_rsi_ema7,slope_obv_ema7
count,18737,18737.000000,18737.000000,18737.000000,18737.000000,18737.000000,18737,1.873700e+04,1.873700e+04,18737.000000,...,18715.000000,18737.000000,18737.000000,18737.0,18737.000000,18737.000000,18724.000000,1.873700e+04,18715.000000,18728.000000
mean,2021-11-27 20:11:20.151571712,36851.506206,37158.718998,36522.644400,36854.919229,10285.335105,2021-11-28 00:11:11.874962688,2.944854e+08,3.244524e+05,5107.098768,...,-0.000002,0.256178,2.871324,0.0,0.016011,0.453648,51.239814,1.436217e+06,0.000570,160.034525
min,2017-08-17 04:00:00,2870.900000,3148.000000,2817.000000,2919.000000,0.000000,2017-08-17 07:59:59.999000,0.000000e+00,0.000000e+00,0.000000,...,-6.597144,0.000000,0.000000,0.0,0.000000,-100.000000,9.434184,-8.762407e+05,-5.002780,-91121.046679
25%,2019-10-09 08:00:00,9205.100000,9273.200000,9125.310000,9205.170000,3368.923010,2019-10-09 11:59:59.999000064,5.959047e+07,6.764500e+04,1662.863627,...,-0.951393,0.000000,0.000000,0.0,0.000000,0.000000,43.214178,-5.666638e+03,-0.719774,-1160.012597
50%,2021-11-28 04:00:00,26786.010000,26904.980000,26605.050000,26795.010000,5972.525580,2021-11-28 07:59:59.999000064,1.717739e+08,1.740810e+05,2987.005580,...,0.012481,0.000000,0.000000,0.0,0.000000,0.000000,50.743987,1.634566e+06,0.004796,32.537625
75%,2024-01-17 20:00:00,57887.960000,58400.000000,57267.980000,57889.100000,10970.361240,2024-01-17 23:59:59.999000064,3.954179e+08,3.924230e+05,5447.199101,...,0.964620,0.000000,0.000000,0.0,0.000000,0.000000,59.232702,3.023454e+06,0.725570,1307.448533
max,2026-03-08 12:00:00,125410.800000,126199.630000,124800.000000,125410.810000,284711.694213,2026-03-08 15:59:59.999000,5.457624e+09,6.089593e+06,141232.701595,...,8.101799,100.000000,100.000000,0.0,100.000000,100.000000,88.814579,3.396603e+06,5.833594,57083.397618
std,NaN,32392.410501,32593.654889,32177.907028,32392.274919,14209.960973,NaN,3.672437e+08,4.172700e+05,7075.550804,...,1.495564,5.055047,16.700383,0.0,1.265282,27.282781,11.849211,1.408075e+06,1.116010,5278.237856

In [65]:
df_btc_pandas.dtypes

open_time         datetime64[ns]
open                     float64
high                     float64
low                      float64
close                    float64
                       ...
engulfing                  int32
rsi_ema7                 float64
obv_ema7                 float64
slope_rsi_ema7           float64
slope_obv_ema7           float64
Length: 112, dtype: object

# Vamos criar uma vista temporária para os dados para pudermos utilizar num comando SQL

In [66]:
df_btc.createOrReplaceTempView("xico")

# Vamos confirmar as vistas criadas

In [67]:
spark.catalog.listTables()

[Table(name='xico', catalog=None, namespace=[], description=None, tableType='TEMPORARY', isTemporary=True)]

In [68]:
sql = spark.sql(""" SELECT * FROM xico WHERE close > 50000 """)

In [69]:
df_btc.createOrReplaceTempView("xico2")

In [70]:
sql2 = spark.sql(""" SELECT * FROM xico2 WHERE close > 40000 """)

In [71]:
spark.catalog.listTables()

[Table(name='xico', catalog=None, namespace=[], description=None, tableType='TEMPORARY', isTemporary=True),
 Table(name='xico2', catalog=None, namespace=[], description=None, tableType='TEMPORARY', isTemporary=True)]

In [72]:
sql.show()

+-------------------+--------+--------+--------+--------+------------+--------------------+-------------------+------+--------------+--------------------+------+-------+------------------+------------------+--------------------+------------------+--------------------+--------------------+-------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+-------------------+---------------+---------------+--------------+--------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-------------------+------------------+------------------+------------------+------------------+--------------------+--------------------+---------------------+-------------------+------------------+-------------------+------------------+------------------+------------------+-------------------+-------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+------------------+---------------+------------------+---------------+-----------------------+-------------------------+-----------------+-------------------+--------------------+--------------------+------------------+------------------+-----------------+---------------------+-------------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+--------------------+--------------------+------------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+-----------+------+--------+---------+---------+-----------------+------------------+--------------------+-------------------+
|          open_time|    open|    high|     low|   close|      volume|          close_time|          quote_vol|trades|taker_buy_base|     taker_buy_quote|ignore| symbol|        volume_adi|        volume_obv|          volume_cmf|         volume_fi|           volume_em|       volume_sma_em|         volume_vpt|       volume_vwap|        volume_mfi|        volume_nvi|    volatility_bbm|    volatility_bbh|    volatility_bbl|    volatility_bbw|    volatility_bbp|volatility_bbhi|volatility_bbli|    volatility_kcc|    volatility_kch|    volatility_kcl|    volatility_kcw|     volatility_kcp|volatility_kchi|volatility_kcli|volatility_dcl|volatility_dch|    volatility_dcm|    volatility_dcw|    volatility_dcp|    volatility_atr|     volatility_ui|        trend_macd| trend_macd_signal|    trend_macd_diff|    trend_sma_fast|    trend_sma_slow|    trend_ema_fast|    trend_ema_slow|trend_vortex_ind_pos|trend_vortex_ind_neg|trend_vortex_ind_diff|         trend_trix|  trend_mass_index|          trend_dpo|         trend_kst|     trend_kst_sig|    trend_kst_diff|trend_ichimoku_conv|trend_ichimoku_base|  trend_ichimoku_a|  trend_ichimoku_b|         trend_stc|         trend_adx|     trend_adx_pos|     trend_adx_neg|         trend_cci|trend_visual_ichimoku_a|trend_visual_ichimoku_b|trend_aroon_up|  trend_aroon_down|trend_aroon_ind|     trend_psar_up|trend_psar_down|trend_psar_up_indicator|trend_psar_down_indicator|     momentum_rsi| momentum_stoch_rsi|momentum_stoch_rsi_k|momentum_stoch_rsi_d|      momentum_tsi|       momentum_uo|   momentum_stoch|momentum_stoch_signal|        momentum_wr|       momentum_ao|      momentum_roc|       momentum_ppo|momentum_ppo_signal|  momentum_ppo_hist|     momentum_kama|           others_dr|          others_dlr|         others_cr|            sma200|             sma50|            ema200|             ema50|             slope|          slope_obv|          slope_rsi|morningstar|hammer|piercing|3soldiers|engulfing|         rsi_ema7|          obv_ema7|      slope_rsi_ema7|     slope_obv_ema7|
+-------------------+--------+--------+--------+--------+------------+--------------------+-------------------+------+--------------+--------------------+------+-------+------------------+------------------+--------------------+------------------+--------------------+--------------------+-------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+-------------------+---------------+---------------+--------------+--------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-------------------+------------------+------------------+------------------+------------------+--------------------+--------------------+---------------------+-------------------+------------------+-------------------+------------------+------------------+------------------+-------------------+-------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+------------------+---------------+------------------+---------------+-----------------------+-------------------------+-----------------+-------------------+--------------------+--------------------+------------------+------------------+-----------------+---------------------+-------------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+--------------------+--------------------+------------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+-----------+------+--------+---------+---------+-----------------+------------------+--------------------+-------------------+
|2021-02-17 04:00:00|49657.84|51266.09|49106.75|51112.39|  18385.2057|2021-02-17 07:59:...|9.232460068893126E8|483871|   9858.094347| 4.955397504966604E8|     0|BTCUSDT| 4556939.543938023|2145743.0821419996| 0.10918904599579465|  5192529.81789553| 6.759005058072302E9|2.5922109840473518E8|  667.8010505918969|48631.275799110175| 65.46325139726369| 54732.14955952173|48632.882999999994|  50466.9444102742| 46798.82158972579| 7.542474544534833|  1.17596073558663|            1.0|            0.0|49042.791333333334| 50561.03133333333| 47524.55133333334|  6.19149097644482| 1.1815782309340643|            1.0|            0.0|      45570.79|      51266.09|          48418.44|11.710800694254536| 0.973012835144769|1460.0761506085717|2.0198663607416623| 821.0437535836973| 715.8163674052194|  105.2273861784779| 48950.86583333334|  48275.8326923077|49129.070019949686| 48308.02626636599|  1.0278601042250504|  0.9088533807311147|   0.1190067234939357|0.20294866462683508|24.900404091318734| -830.2229999999909|42.361783209722375| 34.34822209120014| 8.013561118522233| 49134.854999999996|           48418.44|        48776.6475|46893.854999999996|54.577442631264695|22.511684325546412|28.631962178714165|12.182504581470909|201.00406385060924|             46638.3125|              42573.875|         100.0|               8.0|           92.0| 47022.98580261834|           NULL|                    0.0|                      0.0|68.27336741819863|                1.0|  0.8179119446745723|  0.6254573373250679|20.845717754284497| 57.11840965220346| 97.3012835144769|    82.24923048899252| -2.698716485523102|1272.9614117647143| 8.135327223652162| 2.0769136622885216|-0.6105957995640898| 2.6875094618526116|48154.493387407005|   2.930098204939524|  2.8879913644349386|1075.0001724141896|       38174.87085|         47454.236|39603.576392348135|46684.044729579015|121.29753557244634|  3087.131299248512|0.48076805660831334|          0|     0|       0|        0|        0| 61.3348543037262|2120966.6217901567| 0.22617759628245232|  2474.522569606631|
|2021-02-17 08:00:00|51116.77|51678.36|50628.58|51273.46|16605.902546|2021-02-17 11:59:...|8.511523947514669E8|583997|   9018.180688| 4.623094157137021E8|     0|BTCUSDT|4560735.6578790285|    2162348.984688| 0.13106845901194525| 4832841.661493914| 6.113427115375545E9| 2.471241310276264E9|  591.0346086882989|49013.268834081464| 75.86041416331113| 54904.62647421017|        48833.1955|50888.626767649694| 46777.76423235031|  8.41817229695604| 1.093613743842271|            1.0|            0.0|           49315.6|         50852.701|47778.498999999996| 6.233731314229178| 1.1368677139628423|            1.0|            0.0|      45570.79|      51678.36|         48624.575|12.507004584617034| 0.933705221552925|1419.0465355477143|1.7229730072942921| 931.2881463137019| 758.9107231869159| 172.37742312678597|49240.099166666674| 48408.30346153846| 49458.97617072665| 48527.68802441295|   1.263697401706336|  0.8609279947946535|   0.4027694069116825|0.21408479346478557|25.056552909721205| -894.3654999999999| 45.70152711965515| 35.84953861438075| 9.851988505274399| 49340.990000000005|          48624.575|        48982.7825|         47291.825| 77.28872131563234| 24.00178812764697|29.199511216417832|11.532681318917863| 240.6716330613559|             46750.4725|              42573.875|         100.0|               4.0|           96.0| 47362.43413840888|           NULL|                    0.0|                      0.0|68.91211649934262|                1.0|  0.9486967849797461|  0.7870589954619733|23.515574018486642| 59.51499791057688|92.64297057551627|    89.92852379307298|-7.3570294244837235|1489.8731764705808| 7.260683819687013| 3.2670140103628844| 0.1649261624213051|  3.102087847941579| 48458.15287885217|  0.3151290714443311|  0.3146335804704137|1078.7029395469874|       38237.73815|         47547.715|39719.694637200395| 46864.02179900729|126.85182116496924|  5588.324027678882| 1.0128511261316524|          0|     0|       0|        0|        0|63.22916985263031|2131312.2125146175|   0.422845978744753| 3252.9729341247357|
|2021-02-17 12:00:00|51270.86|51633.17| 50542.3|51169.97|16137.047894|2021-02-17 15:59:...| 8.24265063977848E8|427134|   8209.081886| 4.193483920204974E8|     0|BTCUSDT| 4563168.633638859|2146211.9367939997| 0.11543794830391078| 3903860.983201923|-4.44370865854978...| 2.765789835316002E9| 19.759119706418232|49326.903615041134| 74.31918608907975|54793.807352703334|         48955.435| 51247.76945590146| 46663.10054409853| 9.364984524809007|0.9830305181468671|            0.0|            0.0|49615.278000000006|         51145.666|          48084.89| 6.169019147690753|  1.007940469998459|            1.0|            0.0|      45570.79|      51678.36|         48624.575| 12.47577516163425|0.9167606756860749|1386.2288819929422|1.4221470712698856| 998.7933754176847| 806.8872536330698| 191.90612178461492| 49509.36083333334| 48568.85153846153| 49722.20599061486| 48723.41261519717|   1.229810085919902|  0.7794175294700157|   0.4503925564498862|0.22706839018166247| 25.13014210719183|           -298.125|50.471721371387936| 37.90117775912959|12.570543612258348|           49714.18|          48624.575|        49169.3775|          47702.68| 88.64436065781618|25.268114279172572|27.554708269090494|11.328575999965604|189.32315763489746|                46955.9|              42692.795|          96.0|               8.0|           88.0|47794.026724567986|           NULL|                    0.0|                      0.0|67.96530829597954|  0.933763052184507|  0.9779210173948347|  0.9148432490163835| 25.37957842486624|59.899965284135234|89.12474276644264|     93.0229989521453|-10.875257233557367|1901.0513529411764| 6.740131121264327| 3.8784166632306447| 0.9076242625831731| 2.9707924006474715| 48908.38210571862| -0.2018393141402952|-0.20204328419133333|1076.3238536180543|        38301.2226|        47621.0064| 39833.62772538746|47032.882512771714|131.94627856432277|  5887.709838333404| 0.9898476915594491|          0|     0|       0|        0|        0|64.41320446346761| 2135037.143584463|  0.5645964069484263|  3911.657160176813|
|2021-02-17 16:00:00|51169.97| 52395.0| 50780.0|52142.35|12940.181466|2021-02-17 19:59:...|6.669673722869135E8|351365|   6772.994306| 3.492998549036438E8|     0|BTCUSDT| 4572060.100742772|     2159152.11826| 0.13104817194128512| 5143705.650445798| 6.237319601125283E9|2.7732673129880333E9|  213.3306181438624|49579.105115938524| 74.72473182447756|55835.050925713476|        49109.7945| 51790.98570263216|46428.603297367845| 10.91917093089102| 1.065523916575382|            1.0|            0.0| 49915.93466666667| 51341.18466666667| 48490.68466666667| 5.710601271989271| 1.2810613342688408|            1.0|            0.0|      45570.79|       52395.0|48982.895000000004|13.895822756904428|0.9629773995817829| 1409.105993793648|1.2477395451247062|  1117.86860191889| 869.0835232902339| 248.78507862865604| 49799.78083333333|48782.434230769235| 50094.53583821257| 48976.66723629368|  1.1858595297591028|  0.7772292405371836|  0.40863028922191924|0.24421364149637878|25.232692950139203| -1198.694500000005| 54.58357276863618|40.481840826392464|14.101731942243717|            50072.5| 48982.895000000004|        49527.6975|           48061.0| 94.32218032890809| 26.85291550948589|29.171350664626072|10.395005284900218|190.54845362655627|                46955.9|                42777.9|         100.0|               4.0|           96.0|48182.460052111186|           NULL|                    0.0|                      0.0|71.87530632533449|                1.0|  0.9779210173948347|  0.9681796065898043|28.288843005205333| 67.32224247840041| 95.3138157577466|    92.36050969990187| -4.686184242253404| 2371.422558823535| 7.162418144365155|  2.567777918886442|  1.239654993843827|  1.328122925042615|49348.549756798006|  1.9002942546184842|   1.882464191667843|1098.6774682240648|38371.389950000004|         47736.235| 39956.10257389106| 47233.25378678067|141.60806918509147|  7362.476954200134| 1.6169102194188028|          0|     0|       0|        0|        0|66.27872992893433| 2141065.887253347|  0.8276748600660194|  4774.362108682663|
|2021-02-17 20:00:00|52142.36|52618.74|51893.34|52119.71| 9568.807216|2021-02-17 23:59:...|4.998083241727605E8|359707|   4626.524713| 2.416768995237344E8|     0|BTCUSDT| 4568463.421702912|    2149583.311044| 0.14809615082373395| 4377942.301043509| 5.068122965097461E9| 3.004534791935533E9| 241.74678708105202| 49808.99683405327| 74.58650965318516| 55810.80756972822|49288.721000000005| 52256.54533256572| 46320.89666743429| 12.04261044860838|0.9769468611965609|            0.0|            0.0|50213.278999999995| 51566.26900000001|48860.289000000004| 5.388972904956084| 1.2045251627876004|            1.0|            0.0|      45570.79|      52618.74|         49094.765|14.299316064622566|0.9291950141530517|1340.7353944142833|1.0895346304409774|1196.6158750817267| 934.5899936485324|  262.0258814331943| 50150.49833333333| 48976.42269230769|50406.101093872174| 49209.48521879045|   1.227292260513796|  0.7762595068515445|   0.4510327536622514| 0.2627496907886437|25.300511720722664| 335.30899999999383| 58.93471302964362|43.523429609518836|15.411283420124782| 50184.369999999995|          49094.765|        49639.5675|48172.869999999995| 97.16109016445404|28.437629590326736|29.235457693573363| 9.996521627081238|175.85902119870445|               46746.95|                42777.9|          96.0|              32.0|           64.0|48687.964845857845|           NULL|                    0.0|                      0.0|71.65600881932922| 0.9872925896534488|  0.9736852139459843|  0.9765090829118837|30.542825872843654| 67.25079366796618|91.11274558691534|    91.85043470370154| -8.887254413084658|2751.3871176470493| 8.784206582608208|-0.4198835873191502| 0.9077472776112316|-1.3276308649303818| 49925.55086936425|-0.04341960038241055|-0.04342902942031657| 1098.157007257488|        38453.9349|        47843.1566| 40077.13349355384| 47424.87952063241|153.20848714931188|  6847.379822236454|  1.901932322877061|          0|     0|       0|        0|        0|67.62304965153305|  2143195.24320101|  1.0962392257687819|  5292.616537071014|
|2021-02-18 00:00:00|52117.67| 52530.0|51933.24|52032.64| 9620.973009|2021-02-18 03:59:...|5.022744526369033E8|301916|   4554.376714|2.3780697178388247E8|     0|BTCUSDT| 4562047.505055245|    2139962.338035|  0.1295830129111695|3632850.8123382037|-1.51469910438026...|2.6747267907680907E9|  -20.2273161535019| 49998.08908276068| 69.41116012431905| 55810.80756972822|        49455.6835| 52638.67106817305| 46272.69593182695|12.872079983175436|0.9048015339059439|            0.0|            0.0|50532.009999999995|         51882.829|49181.191000000006|  5.34638934805877| 1.0554519147272885|            1.0|            0.0|      45570.79|      52618.74|         49094.765|14.251041541059678| 0.916841067260693|1266.3378549728552|1.0692356178748472| 1237.730053484731| 995.2180056157721|  242.5120478689588| 50351.21583333333|49174.979999999996| 50656.33784866107| 49418.60779517634|   1.205907611923064|  0.8077224439972287|  0.39818516792583536|0.28046701770269217|25.321306490922627|-292.22350000000006| 62.05067298154297|46.792663186801015|15.258009794741952| 50184.369999999995|          49094.765|        49639.5675|48172.869999999995| 98.58054508222702|29.909149808250383| 28.27517748543303| 9.668171649825947|143.44083861241887|               46746.95|              42990.535|          92.0|28.000000000000004|           64.0|49238.273367437745|           NULL|                    0.0|                      0.0|70.76181888473327| 0.9354778716767059|   0.974256820443384|  0.9752876839280668| 32.13892006353805|63.407351135928884|89.56211087207399|    91.99622407224534|-10.437889127926011|3021.6446176470563| 4.853717039909899| -2.838948219307025|0.15840817822758035| -2.997356397534605|50437.262610307065| -0.1670577215414304|-0.16719741855784065|1096.1553934606745|        38538.0118|        47942.6058|40196.093757299575| 47605.57601001937|164.43171938231356|  4629.652228715194| 1.8765704304310225|          0|     0|       0|        0|        0| 68.4077419598331|2142387.0169095076|  1.2913220269343404|  5126.875459982039|

# Adicionar uma coluna ao dataframe

Vamos calcular a moving average 7 dias

In [73]:
from pyspark.sql.window import Window
from pyspark.sql.functions import col, avg

window = Window.orderBy('open_time').rowsBetween(-7, 0)
df_btc = df_btc.withColumn('ma7', avg('close').over(window))

In [74]:
df_btc.show()

26/05/08 18:28:05 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:05 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:05 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:06 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:06 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+------------------+
|          open_time|   open|   high|    low|  close|    volume|          close_time|       quote_vol|trades|taker_buy_base|taker_buy_quote|ignore| symbol|         volume_adi|         volume_obv|         volume_cmf|          volume_fi|           volume_em|       volume_sma_em|          volume_vpt|      volume_vwap|        volume_mfi|        volume_nvi|volatility_bbm|   volatility_bbh|    volatility_bbl|    volatility_bbw|    volatility_bbp|volatility_bbhi|volatility_bbli|    volatility_kcc|    volatility_kch|    volatility_kcl|    volatility_kcw|      volatility_kcp|volatility_kchi|volatility_kcli|volatility_dcl|volatility_dch|volatility_dcm|  volatility_dcw|   volatility_dcp|    volatility_atr|    volatility_ui|trend_macd|trend_macd_signal|trend_macd_diff|    trend_sma_fast|trend_sma_slow|   trend_ema_fast|trend_ema_slow|trend_vortex_ind_pos|trend_vortex_ind_neg|trend_vortex_ind_diff|trend_trix|trend_mass_index|        trend_dpo|         trend_kst|     trend_kst_sig|    trend_kst_diff|trend_ichimoku_conv|trend_ichimoku_base|trend_ichimoku_a|  trend_ichimoku_b|trend_stc|trend_adx|     trend_adx_pos|     trend_adx_neg|         trend_cci|trend_visual_ichimoku_a|trend_visual_ichimoku_b|trend_aroon_up|trend_aroon_down|trend_aroon_ind|    trend_psar_up|  trend_psar_down|trend_psar_up_indicator|trend_psar_down_indicator|      momentum_rsi|momentum_stoch_rsi|momentum_stoch_rsi_k|momentum_stoch_rsi_d|momentum_tsi|momentum_uo|    momentum_stoch|momentum_stoch_signal|        momentum_wr|momentum_ao|       momentum_roc|momentum_ppo|momentum_ppo_signal|momentum_ppo_hist|     momentum_kama|          others_dr|         others_dlr|           others_cr|sma200|sma50|            ema200|             ema50|              slope|          slope_obv|slope_rsi|morningstar|hammer|piercing|3soldiers|engulfing|          rsi_ema7|           obv_ema7|slope_rsi_ema7|     slope_obv_ema7|               ma7|
+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+------------------+
|2017-08-17 04:00:00|4261.48|4349.99|4261.32|4349.99| 82.088865|2017-08-17 07:59:...| 353194.33293028|   334|     64.013727|275647.42191079|     0|BTCUSDT|          82.088865|          82.088865|               NULL|               NULL|                NULL|                NULL|  -71.42359467918801|             NULL|              NULL|            1000.0|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4409.1033333333335| 4231.763333333333|              NULL|   0.666666666666665|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4305.655|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -88.19698946294015|               NULL|                 0.0|  NULL| NULL|           4349.99|           4349.99|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|          82.088865|          NULL|               NULL|           4349.99|
|2017-08-17 08:00:00|4333.32|4485.39|4333.32| 4427.3| 63.619882|2017-08-17 11:59:...| 282501.15774965|   248|     58.787633|261054.05115395|     0|BTCUSDT|  97.10377632360104|         145.708747|               NULL|               NULL|2.478731255741736E10|                NULL|    -71.269226146657|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4488.255| 4247.514999999999|              NULL|  0.7468015286200891|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|   1.77724546493212|  1.761637118809567|    1.77724546493212|  NULL| NULL| 4350.759253731344| 4353.021764705883|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  97.99383549999999|          NULL|               NULL|          4388.645|
|2017-08-17 12:00:00|4436.06|4485.39|4333.42|4352.34|174.562001|2017-08-17 15:59:...| 774238.79831726|   858|    125.184133| 555419.7580611|     0|BTCUSDT| -33.99289521768992| -28.85325400000002|               NULL|               NULL|   4352894.648605486|                NULL| -1.8248823285697195|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4506.2877777777785| 4244.481111111111|              NULL| 0.41197915340412267|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4349.99|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -1.693131253811575| -1.707628593342747|0.054023112696821585|  NULL| NULL| 4350.774982549938| 4352.995028835064|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  66.28206312499998|          NULL|               NULL| 4376.543333333334|
|2017-08-17 16:00:00|4352.33|4354.84|4200.74|4325.23|225.109716|2017-08-17 19:59:...| 965291.09880366|   986|    165.036363|707808.20092154|     0|BTCUSDT| 104.60807722929104|         -253.96297|               NULL|               NULL|-9.009771706166643E9|                NULL|  -4.357734674578788|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4491.641666666666| 4218.236666666667|              NULL|  0.3913364178904299|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|          4333.42|             NULL|                    1.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -0.622883322534562|-0.6248313341412626| -0.5691967107970375|  NULL| NULL|4350.5208036190925| 4351.906204174865|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-13.779195156250019|          NULL|               NULL|          4363.715|
|2017-08-17 20:00:00|4307.56|4369.69|4258.56|4285.08|249.769913|2017-08-17 23:59:...|1079544.66293121|  1001|    203.226685|878286.96855663|     0|BTCUSDT|-25.951935784027967|        -503.732883|               NULL|               NULL| 1.616651301792292E9|                NULL| -3.7207208761609114|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4476.428|          4213.252|              NULL| 0.27292762257956527|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|-0.9282743345440547|-0.9326096506869774| -1.4921873383616946|  NULL| NULL| 4349.869651344276| 4349.285568717027|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL| -136.2676171171875|          NULL|               NULL|          4347.988|
|2017-08-18 00:00:00|4285.08|4340.62|4134.61|4292.39|276.193043|2017-08-18 03:59:...|1175805.57438953|  1036|     214.65557|915578.05399653|     0|BTCUSDT| 120.91932221631313|-227.53984000000003|               NULL|               NULL|-5.706814671649808E9|                NULL| -1.8473869986577731|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4474.003888888889| 4186.020555555556|              NULL| 0.36935972374944537|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.17059191426997966|0.17044657153579834|  -1.324140975036714|  NULL| NULL| 4349.297714514979|  4347.05436994381|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-159.08567283789063|          NULL|               NULL| 4338.721666666667|
|2017-08-18 04:00:00|4292.39|4340.62|4234.43|4300.25|248.389029|2017-08-18 07:59:...|1063954.72616754|  1135|    203.646699|872408.75176393|     0|BTCUSDT| 180.44941721631292| 20.849188999999967|               NULL|               NULL|2.1337266470009882E9|                NULL|  0.9259999938947068|             NULL|              NULL|1019.6361463207544|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|           4463.14| 4185.957142857143|              NULL| 0.41233739460284097|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4369.69|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.18311476822934214|0.18294731752437343| -1.1434509044848329|  NULL| NULL| 4348.809677554631| 4345.218904455818|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-114.10195737841798|          NULL|               NULL| 4333.225714285714|

```
partitionBy = controla as linhas que ficam na mesma partição. Se estivermos num ambiente distribuido é importante que por exemplo os mesmos symbols sejam processados na mesmo equipamento. 
```

# Vamos fazer o drop de uma coluna

Para tornar a alteração assigna-se novamente ao Spark Dataframe. No pandas temos inplace=True

In [75]:
df_btc.drop('ma7').show()

+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+
|          open_time|   open|   high|    low|  close|    volume|          close_time|       quote_vol|trades|taker_buy_base|taker_buy_quote|ignore| symbol|         volume_adi|         volume_obv|         volume_cmf|          volume_fi|           volume_em|       volume_sma_em|          volume_vpt|      volume_vwap|        volume_mfi|        volume_nvi|volatility_bbm|   volatility_bbh|    volatility_bbl|    volatility_bbw|    volatility_bbp|volatility_bbhi|volatility_bbli|    volatility_kcc|    volatility_kch|    volatility_kcl|    volatility_kcw|      volatility_kcp|volatility_kchi|volatility_kcli|volatility_dcl|volatility_dch|volatility_dcm|  volatility_dcw|   volatility_dcp|    volatility_atr|    volatility_ui|trend_macd|trend_macd_signal|trend_macd_diff|    trend_sma_fast|trend_sma_slow|   trend_ema_fast|trend_ema_slow|trend_vortex_ind_pos|trend_vortex_ind_neg|trend_vortex_ind_diff|trend_trix|trend_mass_index|        trend_dpo|         trend_kst|     trend_kst_sig|    trend_kst_diff|trend_ichimoku_conv|trend_ichimoku_base|trend_ichimoku_a|  trend_ichimoku_b|trend_stc|trend_adx|     trend_adx_pos|     trend_adx_neg|         trend_cci|trend_visual_ichimoku_a|trend_visual_ichimoku_b|trend_aroon_up|trend_aroon_down|trend_aroon_ind|    trend_psar_up|  trend_psar_down|trend_psar_up_indicator|trend_psar_down_indicator|      momentum_rsi|momentum_stoch_rsi|momentum_stoch_rsi_k|momentum_stoch_rsi_d|momentum_tsi|momentum_uo|    momentum_stoch|momentum_stoch_signal|        momentum_wr|momentum_ao|       momentum_roc|momentum_ppo|momentum_ppo_signal|momentum_ppo_hist|     momentum_kama|          others_dr|         others_dlr|           others_cr|sma200|sma50|            ema200|             ema50|              slope|          slope_obv|slope_rsi|morningstar|hammer|piercing|3soldiers|engulfing|          rsi_ema7|           obv_ema7|slope_rsi_ema7|     slope_obv_ema7|
+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+
|2017-08-17 04:00:00|4261.48|4349.99|4261.32|4349.99| 82.088865|2017-08-17 07:59:...| 353194.33293028|   334|     64.013727|275647.42191079|     0|BTCUSDT|          82.088865|          82.088865|               NULL|               NULL|                NULL|                NULL|  -71.42359467918801|             NULL|              NULL|            1000.0|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4409.1033333333335| 4231.763333333333|              NULL|   0.666666666666665|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4305.655|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -88.19698946294015|               NULL|                 0.0|  NULL| NULL|           4349.99|           4349.99|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|          82.088865|          NULL|               NULL|
|2017-08-17 08:00:00|4333.32|4485.39|4333.32| 4427.3| 63.619882|2017-08-17 11:59:...| 282501.15774965|   248|     58.787633|261054.05115395|     0|BTCUSDT|  97.10377632360104|         145.708747|               NULL|               NULL|2.478731255741736E10|                NULL|    -71.269226146657|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4488.255| 4247.514999999999|              NULL|  0.7468015286200891|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|   1.77724546493212|  1.761637118809567|    1.77724546493212|  NULL| NULL| 4350.759253731344| 4353.021764705883|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  97.99383549999999|          NULL|               NULL|
|2017-08-17 12:00:00|4436.06|4485.39|4333.42|4352.34|174.562001|2017-08-17 15:59:...| 774238.79831726|   858|    125.184133| 555419.7580611|     0|BTCUSDT| -33.99289521768992| -28.85325400000002|               NULL|               NULL|   4352894.648605486|                NULL| -1.8248823285697195|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4506.2877777777785| 4244.481111111111|              NULL| 0.41197915340412267|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4349.99|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -1.693131253811575| -1.707628593342747|0.054023112696821585|  NULL| NULL| 4350.774982549938| 4352.995028835064|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  66.28206312499998|          NULL|               NULL|
|2017-08-17 16:00:00|4352.33|4354.84|4200.74|4325.23|225.109716|2017-08-17 19:59:...| 965291.09880366|   986|    165.036363|707808.20092154|     0|BTCUSDT| 104.60807722929104|         -253.96297|               NULL|               NULL|-9.009771706166643E9|                NULL|  -4.357734674578788|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4491.641666666666| 4218.236666666667|              NULL|  0.3913364178904299|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|          4333.42|             NULL|                    1.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -0.622883322534562|-0.6248313341412626| -0.5691967107970375|  NULL| NULL|4350.5208036190925| 4351.906204174865|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-13.779195156250019|          NULL|               NULL|
|2017-08-17 20:00:00|4307.56|4369.69|4258.56|4285.08|249.769913|2017-08-17 23:59:...|1079544.66293121|  1001|    203.226685|878286.96855663|     0|BTCUSDT|-25.951935784027967|        -503.732883|               NULL|               NULL| 1.616651301792292E9|                NULL| -3.7207208761609114|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4476.428|          4213.252|              NULL| 0.27292762257956527|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|-0.9282743345440547|-0.9326096506869774| -1.4921873383616946|  NULL| NULL| 4349.869651344276| 4349.285568717027|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL| -136.2676171171875|          NULL|               NULL|
|2017-08-18 00:00:00|4285.08|4340.62|4134.61|4292.39|276.193043|2017-08-18 03:59:...|1175805.57438953|  1036|     214.65557|915578.05399653|     0|BTCUSDT| 120.91932221631313|-227.53984000000003|               NULL|               NULL|-5.706814671649808E9|                NULL| -1.8473869986577731|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4474.003888888889| 4186.020555555556|              NULL| 0.36935972374944537|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.17059191426997966|0.17044657153579834|  -1.324140975036714|  NULL| NULL| 4349.297714514979|  4347.05436994381|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-159.08567283789063|          NULL|               NULL|
|2017-08-18 04:00:00|4292.39|4340.62|4234.43|4300.25|248.389029|2017-08-18 07:59:...|1063954.72616754|  1135|    203.646699|872408.75176393|     0|BTCUSDT| 180.44941721631292| 20.849188999999967|               NULL|               NULL|2.1337266470009882E9|                NULL|  0.9259999938947068|             NULL|              NULL|1019.6361463207544|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|           4463.14| 4185.957142857143|              NULL| 0.41233739460284097|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4369.69|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.18311476822934214|0.18294731752437343| -1.1434509044848329|  NULL| NULL| 4348.809677554631| 4345.218904455818|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-114.10195737841798|          NULL|               NULL|

# Mudar o nome a uma coluna

In [76]:
df_btc.withColumnRenamed('ma7','moving_average_7').show()

26/05/08 18:28:14 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:14 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:14 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+------------------+
|          open_time|   open|   high|    low|  close|    volume|          close_time|       quote_vol|trades|taker_buy_base|taker_buy_quote|ignore| symbol|         volume_adi|         volume_obv|         volume_cmf|          volume_fi|           volume_em|       volume_sma_em|          volume_vpt|      volume_vwap|        volume_mfi|        volume_nvi|volatility_bbm|   volatility_bbh|    volatility_bbl|    volatility_bbw|    volatility_bbp|volatility_bbhi|volatility_bbli|    volatility_kcc|    volatility_kch|    volatility_kcl|    volatility_kcw|      volatility_kcp|volatility_kchi|volatility_kcli|volatility_dcl|volatility_dch|volatility_dcm|  volatility_dcw|   volatility_dcp|    volatility_atr|    volatility_ui|trend_macd|trend_macd_signal|trend_macd_diff|    trend_sma_fast|trend_sma_slow|   trend_ema_fast|trend_ema_slow|trend_vortex_ind_pos|trend_vortex_ind_neg|trend_vortex_ind_diff|trend_trix|trend_mass_index|        trend_dpo|         trend_kst|     trend_kst_sig|    trend_kst_diff|trend_ichimoku_conv|trend_ichimoku_base|trend_ichimoku_a|  trend_ichimoku_b|trend_stc|trend_adx|     trend_adx_pos|     trend_adx_neg|         trend_cci|trend_visual_ichimoku_a|trend_visual_ichimoku_b|trend_aroon_up|trend_aroon_down|trend_aroon_ind|    trend_psar_up|  trend_psar_down|trend_psar_up_indicator|trend_psar_down_indicator|      momentum_rsi|momentum_stoch_rsi|momentum_stoch_rsi_k|momentum_stoch_rsi_d|momentum_tsi|momentum_uo|    momentum_stoch|momentum_stoch_signal|        momentum_wr|momentum_ao|       momentum_roc|momentum_ppo|momentum_ppo_signal|momentum_ppo_hist|     momentum_kama|          others_dr|         others_dlr|           others_cr|sma200|sma50|            ema200|             ema50|              slope|          slope_obv|slope_rsi|morningstar|hammer|piercing|3soldiers|engulfing|          rsi_ema7|           obv_ema7|slope_rsi_ema7|     slope_obv_ema7|  moving_average_7|
+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+------------------+
|2017-08-17 04:00:00|4261.48|4349.99|4261.32|4349.99| 82.088865|2017-08-17 07:59:...| 353194.33293028|   334|     64.013727|275647.42191079|     0|BTCUSDT|          82.088865|          82.088865|               NULL|               NULL|                NULL|                NULL|  -71.42359467918801|             NULL|              NULL|            1000.0|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4409.1033333333335| 4231.763333333333|              NULL|   0.666666666666665|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4305.655|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -88.19698946294015|               NULL|                 0.0|  NULL| NULL|           4349.99|           4349.99|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|          82.088865|          NULL|               NULL|           4349.99|
|2017-08-17 08:00:00|4333.32|4485.39|4333.32| 4427.3| 63.619882|2017-08-17 11:59:...| 282501.15774965|   248|     58.787633|261054.05115395|     0|BTCUSDT|  97.10377632360104|         145.708747|               NULL|               NULL|2.478731255741736E10|                NULL|    -71.269226146657|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4488.255| 4247.514999999999|              NULL|  0.7468015286200891|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|   1.77724546493212|  1.761637118809567|    1.77724546493212|  NULL| NULL| 4350.759253731344| 4353.021764705883|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  97.99383549999999|          NULL|               NULL|          4388.645|
|2017-08-17 12:00:00|4436.06|4485.39|4333.42|4352.34|174.562001|2017-08-17 15:59:...| 774238.79831726|   858|    125.184133| 555419.7580611|     0|BTCUSDT| -33.99289521768992| -28.85325400000002|               NULL|               NULL|   4352894.648605486|                NULL| -1.8248823285697195|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4506.2877777777785| 4244.481111111111|              NULL| 0.41197915340412267|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4349.99|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -1.693131253811575| -1.707628593342747|0.054023112696821585|  NULL| NULL| 4350.774982549938| 4352.995028835064|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  66.28206312499998|          NULL|               NULL| 4376.543333333334|
|2017-08-17 16:00:00|4352.33|4354.84|4200.74|4325.23|225.109716|2017-08-17 19:59:...| 965291.09880366|   986|    165.036363|707808.20092154|     0|BTCUSDT| 104.60807722929104|         -253.96297|               NULL|               NULL|-9.009771706166643E9|                NULL|  -4.357734674578788|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4491.641666666666| 4218.236666666667|              NULL|  0.3913364178904299|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|          4333.42|             NULL|                    1.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -0.622883322534562|-0.6248313341412626| -0.5691967107970375|  NULL| NULL|4350.5208036190925| 4351.906204174865|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-13.779195156250019|          NULL|               NULL|          4363.715|
|2017-08-17 20:00:00|4307.56|4369.69|4258.56|4285.08|249.769913|2017-08-17 23:59:...|1079544.66293121|  1001|    203.226685|878286.96855663|     0|BTCUSDT|-25.951935784027967|        -503.732883|               NULL|               NULL| 1.616651301792292E9|                NULL| -3.7207208761609114|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4476.428|          4213.252|              NULL| 0.27292762257956527|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|-0.9282743345440547|-0.9326096506869774| -1.4921873383616946|  NULL| NULL| 4349.869651344276| 4349.285568717027|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL| -136.2676171171875|          NULL|               NULL|          4347.988|
|2017-08-18 00:00:00|4285.08|4340.62|4134.61|4292.39|276.193043|2017-08-18 03:59:...|1175805.57438953|  1036|     214.65557|915578.05399653|     0|BTCUSDT| 120.91932221631313|-227.53984000000003|               NULL|               NULL|-5.706814671649808E9|                NULL| -1.8473869986577731|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4474.003888888889| 4186.020555555556|              NULL| 0.36935972374944537|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.17059191426997966|0.17044657153579834|  -1.324140975036714|  NULL| NULL| 4349.297714514979|  4347.05436994381|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-159.08567283789063|          NULL|               NULL| 4338.721666666667|
|2017-08-18 04:00:00|4292.39|4340.62|4234.43|4300.25|248.389029|2017-08-18 07:59:...|1063954.72616754|  1135|    203.646699|872408.75176393|     0|BTCUSDT| 180.44941721631292| 20.849188999999967|               NULL|               NULL|2.1337266470009882E9|                NULL|  0.9259999938947068|             NULL|              NULL|1019.6361463207544|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|           4463.14| 4185.957142857143|              NULL| 0.41233739460284097|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4369.69|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.18311476822934214|0.18294731752437343| -1.1434509044848329|  NULL| NULL| 4348.809677554631| 4345.218904455818|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-114.10195737841798|          NULL|               NULL| 4333.225714285714|

26/05/08 18:28:15 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:15 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

In [77]:
df = df_btc.withColumnRenamed('ma7','moving_average_7').show()

26/05/08 18:28:15 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:15 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:15 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+------------------+
|          open_time|   open|   high|    low|  close|    volume|          close_time|       quote_vol|trades|taker_buy_base|taker_buy_quote|ignore| symbol|         volume_adi|         volume_obv|         volume_cmf|          volume_fi|           volume_em|       volume_sma_em|          volume_vpt|      volume_vwap|        volume_mfi|        volume_nvi|volatility_bbm|   volatility_bbh|    volatility_bbl|    volatility_bbw|    volatility_bbp|volatility_bbhi|volatility_bbli|    volatility_kcc|    volatility_kch|    volatility_kcl|    volatility_kcw|      volatility_kcp|volatility_kchi|volatility_kcli|volatility_dcl|volatility_dch|volatility_dcm|  volatility_dcw|   volatility_dcp|    volatility_atr|    volatility_ui|trend_macd|trend_macd_signal|trend_macd_diff|    trend_sma_fast|trend_sma_slow|   trend_ema_fast|trend_ema_slow|trend_vortex_ind_pos|trend_vortex_ind_neg|trend_vortex_ind_diff|trend_trix|trend_mass_index|        trend_dpo|         trend_kst|     trend_kst_sig|    trend_kst_diff|trend_ichimoku_conv|trend_ichimoku_base|trend_ichimoku_a|  trend_ichimoku_b|trend_stc|trend_adx|     trend_adx_pos|     trend_adx_neg|         trend_cci|trend_visual_ichimoku_a|trend_visual_ichimoku_b|trend_aroon_up|trend_aroon_down|trend_aroon_ind|    trend_psar_up|  trend_psar_down|trend_psar_up_indicator|trend_psar_down_indicator|      momentum_rsi|momentum_stoch_rsi|momentum_stoch_rsi_k|momentum_stoch_rsi_d|momentum_tsi|momentum_uo|    momentum_stoch|momentum_stoch_signal|        momentum_wr|momentum_ao|       momentum_roc|momentum_ppo|momentum_ppo_signal|momentum_ppo_hist|     momentum_kama|          others_dr|         others_dlr|           others_cr|sma200|sma50|            ema200|             ema50|              slope|          slope_obv|slope_rsi|morningstar|hammer|piercing|3soldiers|engulfing|          rsi_ema7|           obv_ema7|slope_rsi_ema7|     slope_obv_ema7|  moving_average_7|
+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+------------------+
|2017-08-17 04:00:00|4261.48|4349.99|4261.32|4349.99| 82.088865|2017-08-17 07:59:...| 353194.33293028|   334|     64.013727|275647.42191079|     0|BTCUSDT|          82.088865|          82.088865|               NULL|               NULL|                NULL|                NULL|  -71.42359467918801|             NULL|              NULL|            1000.0|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4409.1033333333335| 4231.763333333333|              NULL|   0.666666666666665|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4305.655|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -88.19698946294015|               NULL|                 0.0|  NULL| NULL|           4349.99|           4349.99|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|          82.088865|          NULL|               NULL|           4349.99|
|2017-08-17 08:00:00|4333.32|4485.39|4333.32| 4427.3| 63.619882|2017-08-17 11:59:...| 282501.15774965|   248|     58.787633|261054.05115395|     0|BTCUSDT|  97.10377632360104|         145.708747|               NULL|               NULL|2.478731255741736E10|                NULL|    -71.269226146657|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4488.255| 4247.514999999999|              NULL|  0.7468015286200891|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|   1.77724546493212|  1.761637118809567|    1.77724546493212|  NULL| NULL| 4350.759253731344| 4353.021764705883|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  97.99383549999999|          NULL|               NULL|          4388.645|
|2017-08-17 12:00:00|4436.06|4485.39|4333.42|4352.34|174.562001|2017-08-17 15:59:...| 774238.79831726|   858|    125.184133| 555419.7580611|     0|BTCUSDT| -33.99289521768992| -28.85325400000002|               NULL|               NULL|   4352894.648605486|                NULL| -1.8248823285697195|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4506.2877777777785| 4244.481111111111|              NULL| 0.41197915340412267|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4349.99|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -1.693131253811575| -1.707628593342747|0.054023112696821585|  NULL| NULL| 4350.774982549938| 4352.995028835064|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  66.28206312499998|          NULL|               NULL| 4376.543333333334|
|2017-08-17 16:00:00|4352.33|4354.84|4200.74|4325.23|225.109716|2017-08-17 19:59:...| 965291.09880366|   986|    165.036363|707808.20092154|     0|BTCUSDT| 104.60807722929104|         -253.96297|               NULL|               NULL|-9.009771706166643E9|                NULL|  -4.357734674578788|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4491.641666666666| 4218.236666666667|              NULL|  0.3913364178904299|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|          4333.42|             NULL|                    1.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -0.622883322534562|-0.6248313341412626| -0.5691967107970375|  NULL| NULL|4350.5208036190925| 4351.906204174865|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-13.779195156250019|          NULL|               NULL|          4363.715|
|2017-08-17 20:00:00|4307.56|4369.69|4258.56|4285.08|249.769913|2017-08-17 23:59:...|1079544.66293121|  1001|    203.226685|878286.96855663|     0|BTCUSDT|-25.951935784027967|        -503.732883|               NULL|               NULL| 1.616651301792292E9|                NULL| -3.7207208761609114|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4476.428|          4213.252|              NULL| 0.27292762257956527|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|-0.9282743345440547|-0.9326096506869774| -1.4921873383616946|  NULL| NULL| 4349.869651344276| 4349.285568717027|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL| -136.2676171171875|          NULL|               NULL|          4347.988|
|2017-08-18 00:00:00|4285.08|4340.62|4134.61|4292.39|276.193043|2017-08-18 03:59:...|1175805.57438953|  1036|     214.65557|915578.05399653|     0|BTCUSDT| 120.91932221631313|-227.53984000000003|               NULL|               NULL|-5.706814671649808E9|                NULL| -1.8473869986577731|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4474.003888888889| 4186.020555555556|              NULL| 0.36935972374944537|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.17059191426997966|0.17044657153579834|  -1.324140975036714|  NULL| NULL| 4349.297714514979|  4347.05436994381|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-159.08567283789063|          NULL|               NULL| 4338.721666666667|
|2017-08-18 04:00:00|4292.39|4340.62|4234.43|4300.25|248.389029|2017-08-18 07:59:...|1063954.72616754|  1135|    203.646699|872408.75176393|     0|BTCUSDT| 180.44941721631292| 20.849188999999967|               NULL|               NULL|2.1337266470009882E9|                NULL|  0.9259999938947068|             NULL|              NULL|1019.6361463207544|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|           4463.14| 4185.957142857143|              NULL| 0.41233739460284097|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4369.69|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.18311476822934214|0.18294731752437343| -1.1434509044848329|  NULL| NULL| 4348.809677554631| 4345.218904455818|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-114.10195737841798|          NULL|               NULL| 4333.225714285714|

26/05/08 18:28:16 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:16 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

In [78]:
df_btc.show()

26/05/08 18:28:17 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:17 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:17 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+------------------+
|          open_time|   open|   high|    low|  close|    volume|          close_time|       quote_vol|trades|taker_buy_base|taker_buy_quote|ignore| symbol|         volume_adi|         volume_obv|         volume_cmf|          volume_fi|           volume_em|       volume_sma_em|          volume_vpt|      volume_vwap|        volume_mfi|        volume_nvi|volatility_bbm|   volatility_bbh|    volatility_bbl|    volatility_bbw|    volatility_bbp|volatility_bbhi|volatility_bbli|    volatility_kcc|    volatility_kch|    volatility_kcl|    volatility_kcw|      volatility_kcp|volatility_kchi|volatility_kcli|volatility_dcl|volatility_dch|volatility_dcm|  volatility_dcw|   volatility_dcp|    volatility_atr|    volatility_ui|trend_macd|trend_macd_signal|trend_macd_diff|    trend_sma_fast|trend_sma_slow|   trend_ema_fast|trend_ema_slow|trend_vortex_ind_pos|trend_vortex_ind_neg|trend_vortex_ind_diff|trend_trix|trend_mass_index|        trend_dpo|         trend_kst|     trend_kst_sig|    trend_kst_diff|trend_ichimoku_conv|trend_ichimoku_base|trend_ichimoku_a|  trend_ichimoku_b|trend_stc|trend_adx|     trend_adx_pos|     trend_adx_neg|         trend_cci|trend_visual_ichimoku_a|trend_visual_ichimoku_b|trend_aroon_up|trend_aroon_down|trend_aroon_ind|    trend_psar_up|  trend_psar_down|trend_psar_up_indicator|trend_psar_down_indicator|      momentum_rsi|momentum_stoch_rsi|momentum_stoch_rsi_k|momentum_stoch_rsi_d|momentum_tsi|momentum_uo|    momentum_stoch|momentum_stoch_signal|        momentum_wr|momentum_ao|       momentum_roc|momentum_ppo|momentum_ppo_signal|momentum_ppo_hist|     momentum_kama|          others_dr|         others_dlr|           others_cr|sma200|sma50|            ema200|             ema50|              slope|          slope_obv|slope_rsi|morningstar|hammer|piercing|3soldiers|engulfing|          rsi_ema7|           obv_ema7|slope_rsi_ema7|     slope_obv_ema7|               ma7|
+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+------------------+
|2017-08-17 04:00:00|4261.48|4349.99|4261.32|4349.99| 82.088865|2017-08-17 07:59:...| 353194.33293028|   334|     64.013727|275647.42191079|     0|BTCUSDT|          82.088865|          82.088865|               NULL|               NULL|                NULL|                NULL|  -71.42359467918801|             NULL|              NULL|            1000.0|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4409.1033333333335| 4231.763333333333|              NULL|   0.666666666666665|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4305.655|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -88.19698946294015|               NULL|                 0.0|  NULL| NULL|           4349.99|           4349.99|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|          82.088865|          NULL|               NULL|           4349.99|
|2017-08-17 08:00:00|4333.32|4485.39|4333.32| 4427.3| 63.619882|2017-08-17 11:59:...| 282501.15774965|   248|     58.787633|261054.05115395|     0|BTCUSDT|  97.10377632360104|         145.708747|               NULL|               NULL|2.478731255741736E10|                NULL|    -71.269226146657|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4488.255| 4247.514999999999|              NULL|  0.7468015286200891|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|   1.77724546493212|  1.761637118809567|    1.77724546493212|  NULL| NULL| 4350.759253731344| 4353.021764705883|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  97.99383549999999|          NULL|               NULL|          4388.645|
|2017-08-17 12:00:00|4436.06|4485.39|4333.42|4352.34|174.562001|2017-08-17 15:59:...| 774238.79831726|   858|    125.184133| 555419.7580611|     0|BTCUSDT| -33.99289521768992| -28.85325400000002|               NULL|               NULL|   4352894.648605486|                NULL| -1.8248823285697195|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4506.2877777777785| 4244.481111111111|              NULL| 0.41197915340412267|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4349.99|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -1.693131253811575| -1.707628593342747|0.054023112696821585|  NULL| NULL| 4350.774982549938| 4352.995028835064|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  66.28206312499998|          NULL|               NULL| 4376.543333333334|
|2017-08-17 16:00:00|4352.33|4354.84|4200.74|4325.23|225.109716|2017-08-17 19:59:...| 965291.09880366|   986|    165.036363|707808.20092154|     0|BTCUSDT| 104.60807722929104|         -253.96297|               NULL|               NULL|-9.009771706166643E9|                NULL|  -4.357734674578788|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4491.641666666666| 4218.236666666667|              NULL|  0.3913364178904299|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|          4333.42|             NULL|                    1.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -0.622883322534562|-0.6248313341412626| -0.5691967107970375|  NULL| NULL|4350.5208036190925| 4351.906204174865|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-13.779195156250019|          NULL|               NULL|          4363.715|
|2017-08-17 20:00:00|4307.56|4369.69|4258.56|4285.08|249.769913|2017-08-17 23:59:...|1079544.66293121|  1001|    203.226685|878286.96855663|     0|BTCUSDT|-25.951935784027967|        -503.732883|               NULL|               NULL| 1.616651301792292E9|                NULL| -3.7207208761609114|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4476.428|          4213.252|              NULL| 0.27292762257956527|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|-0.9282743345440547|-0.9326096506869774| -1.4921873383616946|  NULL| NULL| 4349.869651344276| 4349.285568717027|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL| -136.2676171171875|          NULL|               NULL|          4347.988|
|2017-08-18 00:00:00|4285.08|4340.62|4134.61|4292.39|276.193043|2017-08-18 03:59:...|1175805.57438953|  1036|     214.65557|915578.05399653|     0|BTCUSDT| 120.91932221631313|-227.53984000000003|               NULL|               NULL|-5.706814671649808E9|                NULL| -1.8473869986577731|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4474.003888888889| 4186.020555555556|              NULL| 0.36935972374944537|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.17059191426997966|0.17044657153579834|  -1.324140975036714|  NULL| NULL| 4349.297714514979|  4347.05436994381|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-159.08567283789063|          NULL|               NULL| 4338.721666666667|
|2017-08-18 04:00:00|4292.39|4340.62|4234.43|4300.25|248.389029|2017-08-18 07:59:...|1063954.72616754|  1135|    203.646699|872408.75176393|     0|BTCUSDT| 180.44941721631292| 20.849188999999967|               NULL|               NULL|2.1337266470009882E9|                NULL|  0.9259999938947068|             NULL|              NULL|1019.6361463207544|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|           4463.14| 4185.957142857143|              NULL| 0.41233739460284097|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4369.69|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.18311476822934214|0.18294731752437343| -1.1434509044848329|  NULL| NULL| 4348.809677554631| 4345.218904455818|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-114.10195737841798|          NULL|               NULL| 4333.225714285714|

26/05/08 18:28:17 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:17 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

In [79]:
df_btc = df_btc.withColumnRenamed('ma7','moving_average_7')

In [80]:
df_btc.show()

26/05/08 18:28:19 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:19 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:19 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+------------------+
|          open_time|   open|   high|    low|  close|    volume|          close_time|       quote_vol|trades|taker_buy_base|taker_buy_quote|ignore| symbol|         volume_adi|         volume_obv|         volume_cmf|          volume_fi|           volume_em|       volume_sma_em|          volume_vpt|      volume_vwap|        volume_mfi|        volume_nvi|volatility_bbm|   volatility_bbh|    volatility_bbl|    volatility_bbw|    volatility_bbp|volatility_bbhi|volatility_bbli|    volatility_kcc|    volatility_kch|    volatility_kcl|    volatility_kcw|      volatility_kcp|volatility_kchi|volatility_kcli|volatility_dcl|volatility_dch|volatility_dcm|  volatility_dcw|   volatility_dcp|    volatility_atr|    volatility_ui|trend_macd|trend_macd_signal|trend_macd_diff|    trend_sma_fast|trend_sma_slow|   trend_ema_fast|trend_ema_slow|trend_vortex_ind_pos|trend_vortex_ind_neg|trend_vortex_ind_diff|trend_trix|trend_mass_index|        trend_dpo|         trend_kst|     trend_kst_sig|    trend_kst_diff|trend_ichimoku_conv|trend_ichimoku_base|trend_ichimoku_a|  trend_ichimoku_b|trend_stc|trend_adx|     trend_adx_pos|     trend_adx_neg|         trend_cci|trend_visual_ichimoku_a|trend_visual_ichimoku_b|trend_aroon_up|trend_aroon_down|trend_aroon_ind|    trend_psar_up|  trend_psar_down|trend_psar_up_indicator|trend_psar_down_indicator|      momentum_rsi|momentum_stoch_rsi|momentum_stoch_rsi_k|momentum_stoch_rsi_d|momentum_tsi|momentum_uo|    momentum_stoch|momentum_stoch_signal|        momentum_wr|momentum_ao|       momentum_roc|momentum_ppo|momentum_ppo_signal|momentum_ppo_hist|     momentum_kama|          others_dr|         others_dlr|           others_cr|sma200|sma50|            ema200|             ema50|              slope|          slope_obv|slope_rsi|morningstar|hammer|piercing|3soldiers|engulfing|          rsi_ema7|           obv_ema7|slope_rsi_ema7|     slope_obv_ema7|  moving_average_7|
+-------------------+-------+-------+-------+-------+----------+--------------------+----------------+------+--------------+---------------+------+-------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+-----------------+------------------+------------------+--------------+-----------------+------------------+------------------+------------------+---------------+---------------+------------------+------------------+------------------+------------------+--------------------+---------------+---------------+--------------+--------------+--------------+----------------+-----------------+------------------+-----------------+----------+-----------------+---------------+------------------+--------------+-----------------+--------------+--------------------+--------------------+---------------------+----------+----------------+-----------------+------------------+------------------+------------------+-------------------+-------------------+----------------+------------------+---------+---------+------------------+------------------+------------------+-----------------------+-----------------------+--------------+----------------+---------------+-----------------+-----------------+-----------------------+-------------------------+------------------+------------------+--------------------+--------------------+------------+-----------+------------------+---------------------+-------------------+-----------+-------------------+------------+-------------------+-----------------+------------------+-------------------+-------------------+--------------------+------+-----+------------------+------------------+-------------------+-------------------+---------+-----------+------+--------+---------+---------+------------------+-------------------+--------------+-------------------+------------------+
|2017-08-17 04:00:00|4261.48|4349.99|4261.32|4349.99| 82.088865|2017-08-17 07:59:...| 353194.33293028|   334|     64.013727|275647.42191079|     0|BTCUSDT|          82.088865|          82.088865|               NULL|               NULL|                NULL|                NULL|  -71.42359467918801|             NULL|              NULL|            1000.0|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4409.1033333333335| 4231.763333333333|              NULL|   0.666666666666665|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4305.655|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -88.19698946294015|               NULL|                 0.0|  NULL| NULL|           4349.99|           4349.99|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|          82.088865|          NULL|               NULL|           4349.99|
|2017-08-17 08:00:00|4333.32|4485.39|4333.32| 4427.3| 63.619882|2017-08-17 11:59:...| 282501.15774965|   248|     58.787633|261054.05115395|     0|BTCUSDT|  97.10377632360104|         145.708747|               NULL|               NULL|2.478731255741736E10|                NULL|    -71.269226146657|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4488.255| 4247.514999999999|              NULL|  0.7468015286200891|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|             NULL|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|   1.77724546493212|  1.761637118809567|    1.77724546493212|  NULL| NULL| 4350.759253731344| 4353.021764705883|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  97.99383549999999|          NULL|               NULL|          4388.645|
|2017-08-17 12:00:00|4436.06|4485.39|4333.42|4352.34|174.562001|2017-08-17 15:59:...| 774238.79831726|   858|    125.184133| 555419.7580611|     0|BTCUSDT| -33.99289521768992| -28.85325400000002|               NULL|               NULL|   4352894.648605486|                NULL| -1.8248823285697195|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|4506.2877777777785| 4244.481111111111|              NULL| 0.41197915340412267|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|          4373.355|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4349.99|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -1.693131253811575| -1.707628593342747|0.054023112696821585|  NULL| NULL| 4350.774982549938| 4352.995028835064|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|  66.28206312499998|          NULL|               NULL| 4376.543333333334|
|2017-08-17 16:00:00|4352.33|4354.84|4200.74|4325.23|225.109716|2017-08-17 19:59:...| 965291.09880366|   986|    165.036363|707808.20092154|     0|BTCUSDT| 104.60807722929104|         -253.96297|               NULL|               NULL|-9.009771706166643E9|                NULL|  -4.357734674578788|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4491.641666666666| 4218.236666666667|              NULL|  0.3913364178904299|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|          4333.42|             NULL|                    1.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL| -0.622883322534562|-0.6248313341412626| -0.5691967107970375|  NULL| NULL|4350.5208036190925| 4351.906204174865|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-13.779195156250019|          NULL|               NULL|          4363.715|
|2017-08-17 20:00:00|4307.56|4369.69|4258.56|4285.08|249.769913|2017-08-17 23:59:...|1079544.66293121|  1001|    203.226685|878286.96855663|     0|BTCUSDT|-25.951935784027967|        -503.732883|               NULL|               NULL| 1.616651301792292E9|                NULL| -3.7207208761609114|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|          4476.428|          4213.252|              NULL| 0.27292762257956527|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|4343.0650000000005|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      1.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|-0.9282743345440547|-0.9326096506869774| -1.4921873383616946|  NULL| NULL| 4349.869651344276| 4349.285568717027|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL| -136.2676171171875|          NULL|               NULL|          4347.988|
|2017-08-18 00:00:00|4285.08|4340.62|4134.61|4292.39|276.193043|2017-08-18 03:59:...|1175805.57438953|  1036|     214.65557|915578.05399653|     0|BTCUSDT| 120.91932221631313|-227.53984000000003|               NULL|               NULL|-5.706814671649808E9|                NULL| -1.8473869986577731|             NULL|              NULL|1017.7724546493212|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL| 4474.003888888889| 4186.020555555556|              NULL| 0.36935972374944537|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4354.84|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.17059191426997966|0.17044657153579834|  -1.324140975036714|  NULL| NULL| 4349.297714514979|  4347.05436994381|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-159.08567283789063|          NULL|               NULL| 4338.721666666667|
|2017-08-18 04:00:00|4292.39|4340.62|4234.43|4300.25|248.389029|2017-08-18 07:59:...|1063954.72616754|  1135|    203.646699|872408.75176393|     0|BTCUSDT| 180.44941721631292| 20.849188999999967|               NULL|               NULL|2.1337266470009882E9|                NULL|  0.9259999938947068|             NULL|              NULL|1019.6361463207544|          NULL|             NULL|              NULL|              NULL|              NULL|            0.0|            0.0|              NULL|           4463.14| 4185.957142857143|              NULL| 0.41233739460284097|            0.0|            0.0|          NULL|          NULL|          NULL|            NULL|             NULL|               0.0|             NULL|      NULL|             NULL|           NULL|              NULL|          NULL|             NULL|          NULL|                NULL|                NULL|                 NULL|      NULL|            NULL|             NULL|              NULL|              NULL|              NULL|               NULL|               NULL|            NULL|            4310.0|     NULL|      0.0|               0.0|               0.0|              NULL|      36800.77023033349|     36650.080737310906|          NULL|            NULL|           NULL|             NULL|          4369.69|                    0.0|                      0.0|              NULL|              NULL|                NULL|                NULL|        NULL|       NULL|              NULL|                 NULL|               NULL|       NULL|               NULL|        NULL|               NULL|             NULL|              NULL|0.18311476822934214|0.18294731752437343| -1.1434509044848329|  NULL| NULL| 4348.809677554631| 4345.218904455818|               NULL|               NULL|     NULL|          0|     0|       0|        0|        0|              NULL|-114.10195737841798|          NULL|               NULL| 4333.225714285714|

26/05/08 18:28:20 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/05/08 18:28:20 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

In [81]:
# Stop the SparkSession
spark.stop()