# First steps
* PySpark Dataframe
* Reading The Dataset
* Checking the Datatypes of the Column(Schema)
* Selecting Columns And Indexing
* Check Describe option similar to Pandas
* Adding Columns
* Dropping columns
* Renaming Columns

# Check assumptions

# Error no catalog

utilizar where ou which python com o environment ativo

```bash
which python
```
```bash
where python
```

Na localização encontrada adicionar Lib\site-packages\pyspark\jars

In [ ]:
import os

In [42]:
os.environ['HADOOP_HOME'] = "C:/Users/sobre/miniconda3/envs/bigdata/Lib/site-packages/pyspark"

NameError: name 'os' is not defined

In [1]:
import pyspark

In [2]:
pyspark.__version__

'3.5.5'

In [6]:
#import findspark
#findspark.init()

Se der erro:

```Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.net.BindException: Cannot assign requested address: bind: Service 'sparkDriver' failed after 16 retries (on a random free port)! Consider explicitly setting the appropriate binding address for the service 'sparkDriver' (for example spark.driver.bindAddress for SparkDriver) to the correct binding address```

In [3]:
conf = pyspark.SparkConf().set('spark.driver.host','localhost')

In [4]:
# Import PySpark and create a SparkSession
from pyspark.sql import SparkSession

#spark = SparkSession.builder.appName("ImportData").getOrCreate()

spark = SparkSession.builder \
    .appName("ImportData") \
    .config("spark.executor.memory", "4g") \
    .getOrCreate()

your 131072x1 screen size is bogus. expect trouble
25/05/10 10:04:11 WARN Utils: Your hostname, msi-sobreiro resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
25/05/10 10:04:11 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/05/10 10:04:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
25/05/10 10:04:13 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.

In [5]:
spark

# Comandos jupyter notebook


* a = above abre célula acima
* b = bellow abre célula abaixo
* dd = apaga célula
* x corta célula
* v cola célula
* m modo markdown
* y modo código

# Markdown

* \# Titulo 1
* \## Titulo 2
* \* unnumbered bullet
* \1. numbered bullet

1. Item
2. Item
3. Item

[Google](http://www.google.com)

# Dados disponíveis no repositório

* O dataset `btc_01d_usdt_binance.parquet` já está incluído no projeto
* Formato Parquet — otimizado para Big Data (columnar, comprimido)

In [11]:
# linux/mac
!pwd
# windows
!cd

/mnt/g/My Drive/mestrados/big_data/exemplos

In [12]:
import pandas as pd

df_pandas = pd.read_parquet("data/btc_01d_usdt_binance.parquet")

In [13]:
type(df_pandas)

pandas.core.frame.DataFrame

In [14]:
df_pandas.describe()

,Unnamed: 0,open,high,low,close,adj_close,volume
count,1229.000000,1229.000000,1229.000000,1229.000000,1229.000000,1229.000000,1.229000e+03
mean,614.000000,3437.767981,3458.883555,3414.612938,3437.854352,3437.854352,4.235175e+09
std,354.926049,672.382944,675.864967,668.834080,672.511442,672.511442,1.083341e+09
min,0.000000,2290.709961,2300.729980,2191.860107,2237.399902,2237.399902,1.296530e+09
25%,307.000000,2836.699951,2852.419922,2820.429932,2839.250000,2839.250000,3.523520e+09
50%,614.000000,3240.090088,3259.810059,3227.199951,3246.219971,3246.219971,3.996900e+09
75%,921.000000,4074.290039,4083.419922,4033.929932,4067.360107,4067.360107,4.687320e+09
max,1228.000000,4804.509766,4818.620117,4780.040039,4796.560059,4796.560059,9.976520e+09

In [17]:
df_pandas.head()

,Unnamed: 0,date,open,high,low,close,adj_close,volume,symbol
0,0,2018-01-02,2683.729980,2695.889893,2682.360107,2695.810059,2695.810059,3397430000,^GSPC
1,1,2018-01-03,2697.850098,2714.370117,2697.770020,2713.060059,2713.060059,3544030000,^GSPC
2,2,2018-01-04,2719.310059,2729.290039,2719.070068,2723.989990,2723.989990,3697340000,^GSPC
3,3,2018-01-05,2731.330078,2743.449951,2727.919922,2743.149902,2743.149902,3239280000,^GSPC
4,4,2018-01-08,2742.669922,2748.510010,2737.600098,2747.709961,2747.709961,3246160000,^GSPC

In [15]:
df_pandas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1229 entries, 0 to 1228
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1229 non-null   int64
 1   date        1229 non-null   object
 2   open        1229 non-null   float64
 3   high        1229 non-null   float64
 4   low         1229 non-null   float64
 5   close       1229 non-null   float64
 6   adj_close   1229 non-null   float64
 7   volume      1229 non-null   int64
 8   symbol      1229 non-null   object
dtypes: float64(5), int64(2), object(2)
memory usage: 86.5+ KB

In [18]:
# Ler dados BTC em formato Parquet (dados reais da Binance)
df_btc = spark.read.parquet("data/btc_01d_usdt_binance.parquet")

In [19]:
type(df_pandas)

pandas.core.frame.DataFrame

In [20]:
type(df_btc)

pyspark.sql.dataframe.DataFrame

In [21]:
df_btc.head(5)

25/05/10 10:20:01 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

[Row(_c0=0, date=datetime.date(2018, 1, 2), open=2683.72998046875, high=2695.88989257812, low=2682.36010742187, close=2695.81005859375, adj_close=2695.81005859375, volume=3397430000, symbol='^GSPC'),
 Row(_c0=1, date=datetime.date(2018, 1, 3), open=2697.85009765625, high=2714.3701171875, low=2697.77001953125, close=2713.06005859375, adj_close=2713.06005859375, volume=3544030000, symbol='^GSPC'),
 Row(_c0=2, date=datetime.date(2018, 1, 4), open=2719.31005859375, high=2729.2900390625, low=2719.07006835937, close=2723.98999023437, adj_close=2723.98999023437, volume=3697340000, symbol='^GSPC'),
 Row(_c0=3, date=datetime.date(2018, 1, 5), open=2731.330078125, high=2743.44995117187, low=2727.919921875, close=2743.14990234375, adj_close=2743.14990234375, volume=3239280000, symbol='^GSPC'),
 Row(_c0=4, date=datetime.date(2018, 1, 8), open=2742.669921875, high=2748.51000976563, low=2737.60009765625, close=2747.7099609375, adj_close=2747.7099609375, volume=3246160000, symbol='^GSPC')]

In [22]:
df_btc.show(5)

+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
|_c0|      date|            open|            high|             low|           close|       adj_close|    volume|symbol|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
|  0|2018-01-02|2683.72998046875|2695.88989257812|2682.36010742187|2695.81005859375|2695.81005859375|3397430000| ^GSPC|
|  1|2018-01-03|2697.85009765625| 2714.3701171875|2697.77001953125|2713.06005859375|2713.06005859375|3544030000| ^GSPC|
|  2|2018-01-04|2719.31005859375| 2729.2900390625|2719.07006835937|2723.98999023437|2723.98999023437|3697340000| ^GSPC|
|  3|2018-01-05|  2731.330078125|2743.44995117187|  2727.919921875|2743.14990234375|2743.14990234375|3239280000| ^GSPC|
|  4|2018-01-08|  2742.669921875|2748.51000976563|2737.60009765625| 2747.7099609375| 2747.7099609375|3246160000| ^GSPC|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
only showing top 5 rows

25/05/10 10:21:24 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

In [23]:
df_btc.toPandas().head()

25/05/10 10:21:56 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

,_c0,date,open,high,low,close,adj_close,volume,symbol
0,0,2018-01-02,2683.729980,2695.889893,2682.360107,2695.810059,2695.810059,3397430000,^GSPC
1,1,2018-01-03,2697.850098,2714.370117,2697.770020,2713.060059,2713.060059,3544030000,^GSPC
2,2,2018-01-04,2719.310059,2729.290039,2719.070068,2723.989990,2723.989990,3697340000,^GSPC
3,3,2018-01-05,2731.330078,2743.449951,2727.919922,2743.149902,2743.149902,3239280000,^GSPC
4,4,2018-01-08,2742.669922,2748.510010,2737.600098,2747.709961,2747.709961,3246160000,^GSPC

In [24]:
type(df_btc.toPandas().head())

25/05/10 10:22:20 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

pandas.core.frame.DataFrame

In [25]:
df_btc.sample(fraction=0.1).toPandas().head()

25/05/10 10:22:59 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

,_c0,date,open,high,low,close,adj_close,volume,symbol
0,29,2018-02-13,2646.270020,2668.840088,2637.080078,2662.939941,2662.939941,3503540000,^GSPC
1,45,2018-03-08,2732.750000,2740.449951,2722.649902,2738.969971,2738.969971,3206040000,^GSPC
2,53,2018-03-20,2715.050049,2724.219971,2710.050049,2716.939941,2716.939941,3272590000,^GSPC
3,55,2018-03-22,2691.360107,2695.679932,2641.590088,2643.689941,2643.689941,3765460000,^GSPC
4,62,2018-04-03,2592.169922,2619.139893,2575.489990,2614.449951,2614.449951,3395840000,^GSPC

In [26]:
df_btc.show(5)

+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
|_c0|      date|            open|            high|             low|           close|       adj_close|    volume|symbol|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
|  0|2018-01-02|2683.72998046875|2695.88989257812|2682.36010742187|2695.81005859375|2695.81005859375|3397430000| ^GSPC|
|  1|2018-01-03|2697.85009765625| 2714.3701171875|2697.77001953125|2713.06005859375|2713.06005859375|3544030000| ^GSPC|
|  2|2018-01-04|2719.31005859375| 2729.2900390625|2719.07006835937|2723.98999023437|2723.98999023437|3697340000| ^GSPC|
|  3|2018-01-05|  2731.330078125|2743.44995117187|  2727.919921875|2743.14990234375|2743.14990234375|3239280000| ^GSPC|
|  4|2018-01-08|  2742.669921875|2748.51000976563|2737.60009765625| 2747.7099609375| 2747.7099609375|3246160000| ^GSPC|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
only showing top 5 rows

25/05/10 10:23:31 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

In [27]:
df_btc.tail(5)

25/05/10 10:23:40 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

[Row(_c0=1224, date=datetime.date(2022, 11, 10), open=3859.88989257812, high=3958.330078125, low=3859.88989257812, close=3956.3701171875, adj_close=3956.3701171875, volume=5781260000, symbol='^GSPC'),
 Row(_c0=1225, date=datetime.date(2022, 11, 11), open=3963.71997070313, high=4001.47998046875, low=3944.82006835938, close=3992.92993164062, adj_close=3992.92993164062, volume=5593310000, symbol='^GSPC'),
 Row(_c0=1226, date=datetime.date(2022, 11, 14), open=3977.96997070312, high=4008.96997070313, low=3956.39990234375, close=3957.25, adj_close=3957.25, volume=4561930000, symbol='^GSPC'),
 Row(_c0=1227, date=datetime.date(2022, 11, 15), open=4006.40991210938, high=4028.84008789063, low=3953.169921875, close=3991.72998046875, adj_close=3991.72998046875, volume=5015310000, symbol='^GSPC'),
 Row(_c0=1228, date=datetime.date(2022, 11, 16), open=3976.82006835938, high=3983.09008789062, low=3954.34008789063, close=3958.7900390625, adj_close=3958.7900390625, volume=2377496000, symbol='^GSPC')]

In [31]:
# Mostrar as colunas de timestamp e preço de fecho
df_btc[['timestamp','close']].show(10)

+----------+----------------+
|      date|           close|
+----------+----------------+
|2018-01-02|2695.81005859375|
|2018-01-03|2713.06005859375|
|2018-01-04|2723.98999023437|
|2018-01-05|2743.14990234375|
|2018-01-08| 2747.7099609375|
|2018-01-09| 2751.2900390625|
|2018-01-10|2748.22998046875|
|2018-01-11|2767.56005859375|
|2018-01-12|2786.23999023437|
|2018-01-16|  2776.419921875|
+----------+----------------+
only showing top 10 rows

In [32]:
df_btc.take(4)

25/05/10 10:25:35 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

[Row(_c0=0, date=datetime.date(2018, 1, 2), open=2683.72998046875, high=2695.88989257812, low=2682.36010742187, close=2695.81005859375, adj_close=2695.81005859375, volume=3397430000, symbol='^GSPC'),
 Row(_c0=1, date=datetime.date(2018, 1, 3), open=2697.85009765625, high=2714.3701171875, low=2697.77001953125, close=2713.06005859375, adj_close=2713.06005859375, volume=3544030000, symbol='^GSPC'),
 Row(_c0=2, date=datetime.date(2018, 1, 4), open=2719.31005859375, high=2729.2900390625, low=2719.07006835937, close=2723.98999023437, adj_close=2723.98999023437, volume=3697340000, symbol='^GSPC'),
 Row(_c0=3, date=datetime.date(2018, 1, 5), open=2731.330078125, high=2743.44995117187, low=2727.919921875, close=2743.14990234375, adj_close=2743.14990234375, volume=3239280000, symbol='^GSPC')]

In [33]:
df_btc.describe().toPandas()

25/05/10 10:29:36 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
25/05/10 10:29:36 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , open, high, low, close, adj_close, volume, symbol
 Schema: _c0, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

,summary,_c0,open,high,low,close,adj_close,volume,symbol
0,count,1229,1229,1229,1229,1229,1229,1229,1229
1,mean,614.0,3437.767980589529,3458.883554655716,3414.612937585817,3437.854352338029,3437.854352338029,4.235175114727421E9,None
2,stddev,354.9260486354869,672.3829441726768,675.8649665978218,668.8340795160047,672.5114423670053,672.5114423670053,1.0833411150490143E9,None
3,min,0,2290.7099609375,2300.72998046875,2191.86010742187,2237.39990234375,2237.39990234375,1296530000,^GSPC
4,max,1228,4804.509765625,4818.6201171875,4780.0400390625,4796.56005859375,4796.56005859375,9976520000,^GSPC

In [34]:
df_btc.take(1)

25/05/10 10:29:46 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

[Row(_c0=0, date=datetime.date(2018, 1, 2), open=2683.72998046875, high=2695.88989257812, low=2682.36010742187, close=2695.81005859375, adj_close=2695.81005859375, volume=3397430000, symbol='^GSPC')]

In [35]:
df_btc.explain()

== Physical Plan ==
FileScan csv [_c0#17,date#18,open#19,high#20,low#21,close#22,adj_close#23,volume#24L,symbol#25] Batched: false, DataFilters: [], Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/mnt/g/My Drive/mestrados/big_data/exemplos/data/spx500.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<_c0:int,date:date,open:double,high:double,low:double,close:double,adj_close:double,volume:...

# Exemplo com pyspark.pandas

Advantages of pyspark.pandas over pandas:

* Scalability: The biggest advantage is its ability to handle datasets that are far too large to fit into the memory of a single machine. pyspark.pandas leverages the power of Apache Spark to distribute data and computations across a cluster of machines, enabling processing of massive datasets that would overwhelm pandas.
* Distributed Computing: By distributing workloads, pyspark.pandas can often achieve significantly faster processing times than pandas on large datasets. This is especially beneficial for tasks like complex aggregations, joins, or machine learning algorithms.
* Integration with Spark Ecosystem: pyspark.pandas seamlessly integrates with other components of the Spark ecosystem, such as Spark SQL for querying structured data, Spark Streaming for real-time processing, and MLlib for machine learning. This makes it easier to build end-to-end big data pipelines.
* Familiarity: The API of pyspark.pandas is intentionally designed to be very similar to pandas, making it easier for data scientists familiar with pandas to transition to big data analysis.
* pyspark.pandas: The preferred choice for large-scale datasets that exceed the memory capacity of a single machine. It provides scalability, distributed computing capabilities, and integration with the broader Spark ecosystem.

In [36]:
import pyspark.pandas as ps

df_btc_pandas = ps.DataFrame(df_btc)

/home/sobreiro/anaconda3/envs/pyspark/lib/python3.12/site-packages/pyspark/pandas/__init__.py:50: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(

In [37]:
df_btc_pandas.head()

25/05/10 10:35:47 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

   _c0        date         open         high          low        close    adj_close      volume symbol
0    0  2018-01-02  2683.729980  2695.889893  2682.360107  2695.810059  2695.810059  3397430000  ^GSPC
1    1  2018-01-03  2697.850098  2714.370117  2697.770020  2713.060059  2713.060059  3544030000  ^GSPC
2    2  2018-01-04  2719.310059  2729.290039  2719.070068  2723.989990  2723.989990  3697340000  ^GSPC
3    3  2018-01-05  2731.330078  2743.449951  2727.919922  2743.149902  2743.149902  3239280000  ^GSPC
4    4  2018-01-08  2742.669922  2748.510010  2737.600098  2747.709961  2747.709961  3246160000  ^GSPC

In [38]:
df_btc_pandas.describe()

25/05/10 10:36:30 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , open, high, low, close, adj_close, volume
 Schema: _c0, open, high, low, close, adj_close, volume
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

               _c0         open         high          low        close    adj_close        volume
count  1229.000000  1229.000000  1229.000000  1229.000000  1229.000000  1229.000000  1.229000e+03
mean    614.000000  3437.767981  3458.883555  3414.612938  3437.854352  3437.854352  4.235175e+09
std     354.926049   672.382944   675.864967   668.834080   672.511442   672.511442  1.083341e+09
min       0.000000  2290.709961  2300.729980  2191.860107  2237.399902  2237.399902  1.296530e+09
25%     307.000000  2836.699951  2852.419922  2820.429932  2839.250000  2839.250000  3.523520e+09
50%     614.000000  3240.090088  3259.810059  3227.199951  3246.219971  3246.219971  3.996900e+09
75%     921.000000  4074.290039  4083.419922  4033.929932  4067.360107  4067.360107  4.687320e+09
max    1228.000000  4804.509766  4818.620117  4780.040039  4796.560059  4796.560059  9.976520e+09

In [39]:
df_btc_pandas.dtypes

_c0            int32
date          object
open         float64
high         float64
low          float64
close        float64
adj_close    float64
volume         int64
symbol        object
dtype: object

# Vamos criar uma vista temporária para os dados para pudermos utilizar num comando SQL

In [40]:
df_btc.createOrReplaceTempView("xico")

# Vamos confirmar as vistas criadas

In [43]:
spark.catalog.listTables()

[Table(name='xico', catalog=None, namespace=[], description=None, tableType='TEMPORARY', isTemporary=True)]

In [44]:
sql = spark.sql(""" SELECT * FROM xico WHERE close > 50000 """)

In [45]:
df_btc.createOrReplaceTempView("xico2")

In [46]:
sql2 = spark.sql(""" SELECT * FROM xico2 WHERE close > 40000 """)

In [47]:
spark.catalog.listTables()

[Table(name='xico', catalog=None, namespace=[], description=None, tableType='TEMPORARY', isTemporary=True),
 Table(name='xico2', catalog=None, namespace=[], description=None, tableType='TEMPORARY', isTemporary=True)]

In [48]:
sql.show()

+----+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
| _c0|      date|            open|            high|             low|           close|       adj_close|    volume|symbol|
+----+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
| 970|2021-11-08|4701.47998046875|  4714.919921875|4694.39013671875| 4701.7001953125| 4701.7001953125|4269710000| ^GSPC|
| 976|2021-11-16|  4679.419921875| 4714.9501953125|  4679.419921875|4700.89990234375|4700.89990234375|3972640000| ^GSPC|
| 978|2021-11-18|4700.72021484375| 4708.7998046875|4672.77978515625| 4704.5400390625| 4704.5400390625|4226410000| ^GSPC|
| 982|2021-11-24|4675.77978515625| 4702.8701171875|4659.89013671875| 4701.4599609375| 4701.4599609375|3418430000| ^GSPC|
| 991|2021-12-08|4690.85986328125|4705.06005859375|4674.52001953125| 4701.2099609375| 4701.2099609375|4234600000| ^GSPC|
| 993|2021-12-10|4687.64013671875|4713.56982421875|  4670.240234375|4712.02001953125|4712.02001953125|3870110000| ^GSPC|
| 996|2021-12-15| 4636.4599609375|4712.60009765625|4611.22021484375|4709.85009765625|4709.85009765625|4910130000| ^GSPC|
|1002|2021-12-23| 4703.9599609375|  4740.740234375| 4703.9599609375| 4725.7900390625| 4725.7900390625|2913040000| ^GSPC|
|1003|2021-12-27|  4733.990234375|  4791.490234375|  4733.990234375|4791.18994140625|4791.18994140625|2770290000| ^GSPC|
|1004|2021-12-28|  4795.490234375|4807.02001953125| 4780.0400390625|4786.35009765625|4786.35009765625|2707920000| ^GSPC|
|1005|2021-12-29|4788.64013671875|4804.06005859375|  4778.080078125|4793.06005859375|4793.06005859375|2963310000| ^GSPC|
|1006|2021-12-30|4794.22998046875|4808.93017578125|  4775.330078125|4778.72998046875|4778.72998046875|3124950000| ^GSPC|
|1007|2021-12-31| 4775.2099609375|  4786.830078125|         4765.75|4766.18017578125|4766.18017578125|2677820000| ^GSPC|
|1008|2022-01-03|4778.14013671875|4796.64013671875|  4758.169921875|4796.56005859375|4796.56005859375|3831020000| ^GSPC|
|1009|2022-01-04|  4804.509765625| 4818.6201171875|4774.27001953125| 4793.5400390625| 4793.5400390625|4683170000| ^GSPC|
|1010|2022-01-05|  4787.990234375| 4797.7001953125|4699.43994140625|  4700.580078125|  4700.580078125|4887960000| ^GSPC|
|1014|2022-01-11|4669.14013671875| 4714.1298828125|4638.27001953125|4713.06982421875|4713.06982421875|4101590000| ^GSPC|
|1015|2022-01-12|   4728.58984375|  4748.830078125| 4706.7099609375|4726.35009765625|4726.35009765625|4048220000| ^GSPC|
+----+----------+----------------+----------------+----------------+----------------+----------------+----------+------+

25/05/10 11:04:05 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

# Adicionar uma coluna ao dataframe

Vamos calcular a moving average 7 dias

In [50]:
from pyspark.sql.window import Window
from pyspark.sql.functions import col, avg

window = Window.orderBy('timestamp').rowsBetween(-7, 0)
df_btc = df_btc.withColumn('ma7', avg('close').over(window))

In [51]:
df_btc.show()

25/05/10 11:43:00 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
|_c0|      date|            open|            high|             low|           close|       adj_close|    volume|symbol|               ma7|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
|  0|2018-01-02|2683.72998046875|2695.88989257812|2682.36010742187|2695.81005859375|2695.81005859375|3397430000| ^GSPC|  2695.81005859375|
|  1|2018-01-03|2697.85009765625| 2714.3701171875|2697.77001953125|2713.06005859375|2713.06005859375|3544030000| ^GSPC|  2704.43505859375|
|  2|2018-01-04|2719.31005859375| 2729.2900390625|2719.07006835937|2723.98999023437|2723.98999023437|3697340000| ^GSPC| 2710.953369140623|
|  3|2018-01-05|  2731.330078125|2743.44995117187|  2727.919921875|2743.14990234375|2743.14990234375|3239280000| ^GSPC| 2719.002502441405|
|  4|2018-01-08|  2742.669921875|2748.51000976563|2737.60009765625| 2747.7099609375| 2747.7099609375|3246160000| ^GSPC|2724.7439941406237|
|  5|2018-01-09|2751.14990234375|2759.13989257812|2747.86010742188| 2751.2900390625| 2751.2900390625|3467460000| ^GSPC|2729.1683349609366|
|  6|2018-01-10|2745.55004882812|2750.80004882812|2736.06005859375|2748.22998046875|2748.22998046875|3579900000| ^GSPC|2731.8914271763383|
|  7|2018-01-11|2752.96997070313|2767.56005859375|2752.78002929688|2767.56005859375|2767.56005859375|3645690000| ^GSPC|2736.3500061035147|
|  8|2018-01-12|2770.17993164062|2787.85009765625|2769.63989257812|2786.23999023437|2786.23999023437|3587220000| ^GSPC|2747.6537475585924|
|  9|2018-01-16| 2798.9599609375| 2807.5400390625|2768.63989257812|  2776.419921875|  2776.419921875|4362880000| ^GSPC|2755.5737304687486|
| 10|2018-01-17|2784.98999023437| 2807.0400390625| 2778.3798828125|2802.56005859375|2802.56005859375|3790340000| ^GSPC|2765.3949890136714|
| 11|2018-01-18|2802.39990234375|  2805.830078125|2792.56005859375|2798.03002929687|2798.03002929687|3703300000| ^GSPC| 2772.255004882811|
| 12|2018-01-19|2802.60009765625|  2810.330078125|  2798.080078125|2810.30004882812|2810.30004882812|3724230000| ^GSPC| 2780.078765869139|
| 13|2018-01-22|2809.15991210937|2833.03002929688| 2808.1201171875|2832.96997070312|2832.96997070312|3489480000| ^GSPC|2790.2887573242165|
| 14|2018-01-23|2835.05004882812|2842.23999023438|2830.59008789062| 2839.1298828125| 2839.1298828125|3541140000| ^GSPC| 2801.651245117185|
| 15|2018-01-24|  2845.419921875|2852.96997070312|2824.81005859375| 2837.5400390625| 2837.5400390625|4079270000| ^GSPC|2810.3987426757785|
| 16|2018-01-25|2846.23999023438|2848.56005859375|2830.93994140625|         2839.25|         2839.25|3873100000| ^GSPC|2817.0249938964826|
| 17|2018-01-26|2847.47998046875| 2872.8701171875|2846.17993164062| 2872.8701171875| 2872.8701171875|3474680000| ^GSPC| 2829.081268310545|
| 18|2018-01-29|2867.22998046875| 2870.6201171875|2851.47998046875|2853.53002929687|2853.53002929687|3587420000| ^GSPC| 2835.452514648435|
| 19|2018-01-30|2832.73999023437|         2837.75|2818.27001953125|2822.42993164063|2822.42993164063|4012070000| ^GSPC| 2838.502502441405|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
only showing top 20 rows

```
partitionBy = controla as linhas que ficam na mesma partição. Se estivermos num ambiente distribuido é importante que por exemplo os mesmos symbols sejam processados na mesmo equipamento. 
```

# Vamos fazer o drop de uma coluna

Para tornar a alteração assigna-se novamente ao Spark Dataframe. No pandas temos inplace=True

In [56]:
df_btc.drop('ma7').show()

+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
|_c0|      date|            open|            high|             low|           close|       adj_close|    volume|symbol|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
|  0|2018-01-02|2683.72998046875|2695.88989257812|2682.36010742187|2695.81005859375|2695.81005859375|3397430000| ^GSPC|
|  1|2018-01-03|2697.85009765625| 2714.3701171875|2697.77001953125|2713.06005859375|2713.06005859375|3544030000| ^GSPC|
|  2|2018-01-04|2719.31005859375| 2729.2900390625|2719.07006835937|2723.98999023437|2723.98999023437|3697340000| ^GSPC|
|  3|2018-01-05|  2731.330078125|2743.44995117187|  2727.919921875|2743.14990234375|2743.14990234375|3239280000| ^GSPC|
|  4|2018-01-08|  2742.669921875|2748.51000976563|2737.60009765625| 2747.7099609375| 2747.7099609375|3246160000| ^GSPC|
|  5|2018-01-09|2751.14990234375|2759.13989257812|2747.86010742188| 2751.2900390625| 2751.2900390625|3467460000| ^GSPC|
|  6|2018-01-10|2745.55004882812|2750.80004882812|2736.06005859375|2748.22998046875|2748.22998046875|3579900000| ^GSPC|
|  7|2018-01-11|2752.96997070313|2767.56005859375|2752.78002929688|2767.56005859375|2767.56005859375|3645690000| ^GSPC|
|  8|2018-01-12|2770.17993164062|2787.85009765625|2769.63989257812|2786.23999023437|2786.23999023437|3587220000| ^GSPC|
|  9|2018-01-16| 2798.9599609375| 2807.5400390625|2768.63989257812|  2776.419921875|  2776.419921875|4362880000| ^GSPC|
| 10|2018-01-17|2784.98999023437| 2807.0400390625| 2778.3798828125|2802.56005859375|2802.56005859375|3790340000| ^GSPC|
| 11|2018-01-18|2802.39990234375|  2805.830078125|2792.56005859375|2798.03002929687|2798.03002929687|3703300000| ^GSPC|
| 12|2018-01-19|2802.60009765625|  2810.330078125|  2798.080078125|2810.30004882812|2810.30004882812|3724230000| ^GSPC|
| 13|2018-01-22|2809.15991210937|2833.03002929688| 2808.1201171875|2832.96997070312|2832.96997070312|3489480000| ^GSPC|
| 14|2018-01-23|2835.05004882812|2842.23999023438|2830.59008789062| 2839.1298828125| 2839.1298828125|3541140000| ^GSPC|
| 15|2018-01-24|  2845.419921875|2852.96997070312|2824.81005859375| 2837.5400390625| 2837.5400390625|4079270000| ^GSPC|
| 16|2018-01-25|2846.23999023438|2848.56005859375|2830.93994140625|         2839.25|         2839.25|3873100000| ^GSPC|
| 17|2018-01-26|2847.47998046875| 2872.8701171875|2846.17993164062| 2872.8701171875| 2872.8701171875|3474680000| ^GSPC|
| 18|2018-01-29|2867.22998046875| 2870.6201171875|2851.47998046875|2853.53002929687|2853.53002929687|3587420000| ^GSPC|
| 19|2018-01-30|2832.73999023437|         2837.75|2818.27001953125|2822.42993164063|2822.42993164063|4012070000| ^GSPC|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+
only showing top 20 rows

# Mudar o nome a uma coluna

In [58]:
df_btc.withColumnRenamed('ma7','moving_average_7').show()

+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
|_c0|      date|            open|            high|             low|           close|       adj_close|    volume|symbol|  moving_average_7|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
|  0|2018-01-02|2683.72998046875|2695.88989257812|2682.36010742187|2695.81005859375|2695.81005859375|3397430000| ^GSPC|  2695.81005859375|
|  1|2018-01-03|2697.85009765625| 2714.3701171875|2697.77001953125|2713.06005859375|2713.06005859375|3544030000| ^GSPC|  2704.43505859375|
|  2|2018-01-04|2719.31005859375| 2729.2900390625|2719.07006835937|2723.98999023437|2723.98999023437|3697340000| ^GSPC| 2710.953369140623|
|  3|2018-01-05|  2731.330078125|2743.44995117187|  2727.919921875|2743.14990234375|2743.14990234375|3239280000| ^GSPC| 2719.002502441405|
|  4|2018-01-08|  2742.669921875|2748.51000976563|2737.60009765625| 2747.7099609375| 2747.7099609375|3246160000| ^GSPC|2724.7439941406237|
|  5|2018-01-09|2751.14990234375|2759.13989257812|2747.86010742188| 2751.2900390625| 2751.2900390625|3467460000| ^GSPC|2729.1683349609366|
|  6|2018-01-10|2745.55004882812|2750.80004882812|2736.06005859375|2748.22998046875|2748.22998046875|3579900000| ^GSPC|2731.8914271763383|
|  7|2018-01-11|2752.96997070313|2767.56005859375|2752.78002929688|2767.56005859375|2767.56005859375|3645690000| ^GSPC|2736.3500061035147|
|  8|2018-01-12|2770.17993164062|2787.85009765625|2769.63989257812|2786.23999023437|2786.23999023437|3587220000| ^GSPC|2747.6537475585924|
|  9|2018-01-16| 2798.9599609375| 2807.5400390625|2768.63989257812|  2776.419921875|  2776.419921875|4362880000| ^GSPC|2755.5737304687486|
| 10|2018-01-17|2784.98999023437| 2807.0400390625| 2778.3798828125|2802.56005859375|2802.56005859375|3790340000| ^GSPC|2765.3949890136714|
| 11|2018-01-18|2802.39990234375|  2805.830078125|2792.56005859375|2798.03002929687|2798.03002929687|3703300000| ^GSPC| 2772.255004882811|
| 12|2018-01-19|2802.60009765625|  2810.330078125|  2798.080078125|2810.30004882812|2810.30004882812|3724230000| ^GSPC| 2780.078765869139|
| 13|2018-01-22|2809.15991210937|2833.03002929688| 2808.1201171875|2832.96997070312|2832.96997070312|3489480000| ^GSPC|2790.2887573242165|
| 14|2018-01-23|2835.05004882812|2842.23999023438|2830.59008789062| 2839.1298828125| 2839.1298828125|3541140000| ^GSPC| 2801.651245117185|
| 15|2018-01-24|  2845.419921875|2852.96997070312|2824.81005859375| 2837.5400390625| 2837.5400390625|4079270000| ^GSPC|2810.3987426757785|
| 16|2018-01-25|2846.23999023438|2848.56005859375|2830.93994140625|         2839.25|         2839.25|3873100000| ^GSPC|2817.0249938964826|
| 17|2018-01-26|2847.47998046875| 2872.8701171875|2846.17993164062| 2872.8701171875| 2872.8701171875|3474680000| ^GSPC| 2829.081268310545|
| 18|2018-01-29|2867.22998046875| 2870.6201171875|2851.47998046875|2853.53002929687|2853.53002929687|3587420000| ^GSPC| 2835.452514648435|
| 19|2018-01-30|2832.73999023437|         2837.75|2818.27001953125|2822.42993164063|2822.42993164063|4012070000| ^GSPC| 2838.502502441405|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
only showing top 20 rows

In [52]:
df = df_btc.withColumnRenamed('ma7','moving_average_7').show()

+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
|_c0|      date|            open|            high|             low|           close|       adj_close|    volume|symbol|  moving_average_7|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
|  0|2018-01-02|2683.72998046875|2695.88989257812|2682.36010742187|2695.81005859375|2695.81005859375|3397430000| ^GSPC|  2695.81005859375|
|  1|2018-01-03|2697.85009765625| 2714.3701171875|2697.77001953125|2713.06005859375|2713.06005859375|3544030000| ^GSPC|  2704.43505859375|
|  2|2018-01-04|2719.31005859375| 2729.2900390625|2719.07006835937|2723.98999023437|2723.98999023437|3697340000| ^GSPC| 2710.953369140623|
|  3|2018-01-05|  2731.330078125|2743.44995117187|  2727.919921875|2743.14990234375|2743.14990234375|3239280000| ^GSPC| 2719.002502441405|
|  4|2018-01-08|  2742.669921875|2748.51000976563|2737.60009765625| 2747.7099609375| 2747.7099609375|3246160000| ^GSPC|2724.7439941406237|
|  5|2018-01-09|2751.14990234375|2759.13989257812|2747.86010742188| 2751.2900390625| 2751.2900390625|3467460000| ^GSPC|2729.1683349609366|
|  6|2018-01-10|2745.55004882812|2750.80004882812|2736.06005859375|2748.22998046875|2748.22998046875|3579900000| ^GSPC|2731.8914271763383|
|  7|2018-01-11|2752.96997070313|2767.56005859375|2752.78002929688|2767.56005859375|2767.56005859375|3645690000| ^GSPC|2736.3500061035147|
|  8|2018-01-12|2770.17993164062|2787.85009765625|2769.63989257812|2786.23999023437|2786.23999023437|3587220000| ^GSPC|2747.6537475585924|
|  9|2018-01-16| 2798.9599609375| 2807.5400390625|2768.63989257812|  2776.419921875|  2776.419921875|4362880000| ^GSPC|2755.5737304687486|
| 10|2018-01-17|2784.98999023437| 2807.0400390625| 2778.3798828125|2802.56005859375|2802.56005859375|3790340000| ^GSPC|2765.3949890136714|
| 11|2018-01-18|2802.39990234375|  2805.830078125|2792.56005859375|2798.03002929687|2798.03002929687|3703300000| ^GSPC| 2772.255004882811|
| 12|2018-01-19|2802.60009765625|  2810.330078125|  2798.080078125|2810.30004882812|2810.30004882812|3724230000| ^GSPC| 2780.078765869139|
| 13|2018-01-22|2809.15991210937|2833.03002929688| 2808.1201171875|2832.96997070312|2832.96997070312|3489480000| ^GSPC|2790.2887573242165|
| 14|2018-01-23|2835.05004882812|2842.23999023438|2830.59008789062| 2839.1298828125| 2839.1298828125|3541140000| ^GSPC| 2801.651245117185|
| 15|2018-01-24|  2845.419921875|2852.96997070312|2824.81005859375| 2837.5400390625| 2837.5400390625|4079270000| ^GSPC|2810.3987426757785|
| 16|2018-01-25|2846.23999023438|2848.56005859375|2830.93994140625|         2839.25|         2839.25|3873100000| ^GSPC|2817.0249938964826|
| 17|2018-01-26|2847.47998046875| 2872.8701171875|2846.17993164062| 2872.8701171875| 2872.8701171875|3474680000| ^GSPC| 2829.081268310545|
| 18|2018-01-29|2867.22998046875| 2870.6201171875|2851.47998046875|2853.53002929687|2853.53002929687|3587420000| ^GSPC| 2835.452514648435|
| 19|2018-01-30|2832.73999023437|         2837.75|2818.27001953125|2822.42993164063|2822.42993164063|4012070000| ^GSPC| 2838.502502441405|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
only showing top 20 rows

25/05/10 11:45:27 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

In [61]:
df_btc.show()

+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
|_c0|      date|            open|            high|             low|           close|       adj_close|    volume|symbol|               ma7|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
|  0|2018-01-02|2683.72998046875|2695.88989257812|2682.36010742187|2695.81005859375|2695.81005859375|3397430000| ^GSPC|  2695.81005859375|
|  1|2018-01-03|2697.85009765625| 2714.3701171875|2697.77001953125|2713.06005859375|2713.06005859375|3544030000| ^GSPC|  2704.43505859375|
|  2|2018-01-04|2719.31005859375| 2729.2900390625|2719.07006835937|2723.98999023437|2723.98999023437|3697340000| ^GSPC| 2710.953369140623|
|  3|2018-01-05|  2731.330078125|2743.44995117187|  2727.919921875|2743.14990234375|2743.14990234375|3239280000| ^GSPC| 2719.002502441405|
|  4|2018-01-08|  2742.669921875|2748.51000976563|2737.60009765625| 2747.7099609375| 2747.7099609375|3246160000| ^GSPC|2724.7439941406237|
|  5|2018-01-09|2751.14990234375|2759.13989257812|2747.86010742188| 2751.2900390625| 2751.2900390625|3467460000| ^GSPC|2729.1683349609366|
|  6|2018-01-10|2745.55004882812|2750.80004882812|2736.06005859375|2748.22998046875|2748.22998046875|3579900000| ^GSPC|2731.8914271763383|
|  7|2018-01-11|2752.96997070313|2767.56005859375|2752.78002929688|2767.56005859375|2767.56005859375|3645690000| ^GSPC|2736.3500061035147|
|  8|2018-01-12|2770.17993164062|2787.85009765625|2769.63989257812|2786.23999023437|2786.23999023437|3587220000| ^GSPC|2747.6537475585924|
|  9|2018-01-16| 2798.9599609375| 2807.5400390625|2768.63989257812|  2776.419921875|  2776.419921875|4362880000| ^GSPC|2755.5737304687486|
| 10|2018-01-17|2784.98999023437| 2807.0400390625| 2778.3798828125|2802.56005859375|2802.56005859375|3790340000| ^GSPC|2765.3949890136714|
| 11|2018-01-18|2802.39990234375|  2805.830078125|2792.56005859375|2798.03002929687|2798.03002929687|3703300000| ^GSPC| 2772.255004882811|
| 12|2018-01-19|2802.60009765625|  2810.330078125|  2798.080078125|2810.30004882812|2810.30004882812|3724230000| ^GSPC| 2780.078765869139|
| 13|2018-01-22|2809.15991210937|2833.03002929688| 2808.1201171875|2832.96997070312|2832.96997070312|3489480000| ^GSPC|2790.2887573242165|
| 14|2018-01-23|2835.05004882812|2842.23999023438|2830.59008789062| 2839.1298828125| 2839.1298828125|3541140000| ^GSPC| 2801.651245117185|
| 15|2018-01-24|  2845.419921875|2852.96997070312|2824.81005859375| 2837.5400390625| 2837.5400390625|4079270000| ^GSPC|2810.3987426757785|
| 16|2018-01-25|2846.23999023438|2848.56005859375|2830.93994140625|         2839.25|         2839.25|3873100000| ^GSPC|2817.0249938964826|
| 17|2018-01-26|2847.47998046875| 2872.8701171875|2846.17993164062| 2872.8701171875| 2872.8701171875|3474680000| ^GSPC| 2829.081268310545|
| 18|2018-01-29|2867.22998046875| 2870.6201171875|2851.47998046875|2853.53002929687|2853.53002929687|3587420000| ^GSPC| 2835.452514648435|
| 19|2018-01-30|2832.73999023437|         2837.75|2818.27001953125|2822.42993164063|2822.42993164063|4012070000| ^GSPC| 2838.502502441405|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
only showing top 20 rows

In [40]:
df_btc = df_btc.withColumnRenamed('ma7','moving_average_7')

In [41]:
df_btc.show()

+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
|_c0|      date|            open|            high|             low|           close|       adj_close|    volume|symbol|  moving_average_7|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
|  0|2018-01-02|2683.72998046875|2695.88989257812|2682.36010742187|2695.81005859375|2695.81005859375|3397430000| ^GSPC|  2695.81005859375|
|  1|2018-01-03|2697.85009765625| 2714.3701171875|2697.77001953125|2713.06005859375|2713.06005859375|3544030000| ^GSPC|  2704.43505859375|
|  2|2018-01-04|2719.31005859375| 2729.2900390625|2719.07006835937|2723.98999023437|2723.98999023437|3697340000| ^GSPC| 2710.953369140623|
|  3|2018-01-05|  2731.330078125|2743.44995117187|  2727.919921875|2743.14990234375|2743.14990234375|3239280000| ^GSPC| 2719.002502441405|
|  4|2018-01-08|  2742.669921875|2748.51000976563|2737.60009765625| 2747.7099609375| 2747.7099609375|3246160000| ^GSPC|2724.7439941406237|
|  5|2018-01-09|2751.14990234375|2759.13989257812|2747.86010742188| 2751.2900390625| 2751.2900390625|3467460000| ^GSPC|2729.1683349609366|
|  6|2018-01-10|2745.55004882812|2750.80004882812|2736.06005859375|2748.22998046875|2748.22998046875|3579900000| ^GSPC|2731.8914271763383|
|  7|2018-01-11|2752.96997070313|2767.56005859375|2752.78002929688|2767.56005859375|2767.56005859375|3645690000| ^GSPC|2736.3500061035147|
|  8|2018-01-12|2770.17993164062|2787.85009765625|2769.63989257812|2786.23999023437|2786.23999023437|3587220000| ^GSPC|2747.6537475585924|
|  9|2018-01-16| 2798.9599609375| 2807.5400390625|2768.63989257812|  2776.419921875|  2776.419921875|4362880000| ^GSPC|2755.5737304687486|
| 10|2018-01-17|2784.98999023437| 2807.0400390625| 2778.3798828125|2802.56005859375|2802.56005859375|3790340000| ^GSPC|2765.3949890136714|
| 11|2018-01-18|2802.39990234375|  2805.830078125|2792.56005859375|2798.03002929687|2798.03002929687|3703300000| ^GSPC| 2772.255004882811|
| 12|2018-01-19|2802.60009765625|  2810.330078125|  2798.080078125|2810.30004882812|2810.30004882812|3724230000| ^GSPC| 2780.078765869139|
| 13|2018-01-22|2809.15991210937|2833.03002929688| 2808.1201171875|2832.96997070312|2832.96997070312|3489480000| ^GSPC|2790.2887573242165|
| 14|2018-01-23|2835.05004882812|2842.23999023438|2830.59008789062| 2839.1298828125| 2839.1298828125|3541140000| ^GSPC| 2801.651245117185|
| 15|2018-01-24|  2845.419921875|2852.96997070312|2824.81005859375| 2837.5400390625| 2837.5400390625|4079270000| ^GSPC|2810.3987426757785|
| 16|2018-01-25|2846.23999023438|2848.56005859375|2830.93994140625|         2839.25|         2839.25|3873100000| ^GSPC|2817.0249938964826|
| 17|2018-01-26|2847.47998046875| 2872.8701171875|2846.17993164062| 2872.8701171875| 2872.8701171875|3474680000| ^GSPC| 2829.081268310545|
| 18|2018-01-29|2867.22998046875| 2870.6201171875|2851.47998046875|2853.53002929687|2853.53002929687|3587420000| ^GSPC| 2835.452514648435|
| 19|2018-01-30|2832.73999023437|         2837.75|2818.27001953125|2822.42993164063|2822.42993164063|4012070000| ^GSPC| 2838.502502441405|
+---+----------+----------------+----------------+----------------+----------------+----------------+----------+------+------------------+
only showing top 20 rows

25/04/12 08:23:53 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , date, open, high, low, close, adj_close, volume, symbol
 Schema: _c0, date, open, high, low, close, adj_close, volume, symbol
Expected: _c0 but found:
CSV file: file:///mnt/g/My%20Drive/mestrados/big_data/exemplos/data/spx500.csv

In [53]:
# Stop the SparkSession
spark.stop()